# 1 "data/maps/SlateportCity/scripts.pory"

# 2 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_FAT_MAN, 1
# 3 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_MAN_1, 2
# 4 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_RICH_BOY, 3
# 5 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_1, 5
# 6 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_COOK, 6
# 7 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_OLD_WOMAN, 7
# 8 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GIRL, 8
# 9 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_TY, 9
# 10 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GABBY, 10
# 11 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_CAPT_STERN, 11
# 12 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_2, 18
# 13 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_3, 19
# 14 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_4, 26
# 15 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_5, 27
# 16 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_6, 28
# 17 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_7, 29
# 18 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_8, 30
# 19 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_9, 31
# 20 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_GRUNT_11, 33
# 21 "data/maps/SlateportCity/scripts.pory"
.set LOCALID_SCOTT, 35
# 22 "data/maps/SlateportCity/scripts.pory"

# 23 "data/maps/SlateportCity/scripts.pory"
@ Note: LOCALID_SLATEPORT_ENERGY_GURU is a local id for this map used elsewhere. It's defined in event_objects.h
# 24 "data/maps/SlateportCity/scripts.pory"

# 25 "data/maps/SlateportCity/scripts.pory"
SlateportCity_MapScripts::
# 26 "data/maps/SlateportCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SlateportCity_OnTransition
# 27 "data/maps/SlateportCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SlateportCity_OnFrame
# 28 "data/maps/SlateportCity/scripts.pory"
	.byte 0
# 29 "data/maps/SlateportCity/scripts.pory"

# 30 "data/maps/SlateportCity/scripts.pory"
SlateportCity_OnTransition:
# 31 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_SLATEPORT_MUSEUM_1F_STATE, 0
# 32 "data/maps/SlateportCity/scripts.pory"
	call SlateportCity_EventScript_EnterSlateport
# 33 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_MovePeopleForSternInterview
# 34 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE, 1, SlateportCity_EventScript_SetReadyForScottScene
# 35 "data/maps/SlateportCity/scripts.pory"
	end
# 36 "data/maps/SlateportCity/scripts.pory"

# 37 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_EnterSlateport::
# 38 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_VISITED_SLATEPORT_CITY
# 39 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_CONTEST_HALL_STATE, 0
# 40 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER
# 41 "data/maps/SlateportCity/scripts.pory"
	return
# 42 "data/maps/SlateportCity/scripts.pory"

# 43 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_MovePeopleForSternInterview::
# 44 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_CAPT_STERN, 28, 13
# 45 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_OLD_WOMAN, 25, 13
# 46 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_RICH_BOY, 25, 14
# 47 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_COOK, 27, 16
# 48 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_GIRL, 28, 16
# 49 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_FAT_MAN, 29, 16
# 50 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_MAN_1, 31, 14
# 51 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_CAPT_STERN, MOVEMENT_TYPE_FACE_DOWN
# 52 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_OLD_WOMAN, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT
# 53 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_RICH_BOY, MOVEMENT_TYPE_FACE_UP_AND_RIGHT
# 54 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_COOK, MOVEMENT_TYPE_FACE_UP
# 55 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_GIRL, MOVEMENT_TYPE_FACE_UP
# 56 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_FAT_MAN, MOVEMENT_TYPE_FACE_UP
# 57 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_MAN_1, MOVEMENT_TYPE_FACE_LEFT
# 58 "data/maps/SlateportCity/scripts.pory"
	return
# 59 "data/maps/SlateportCity/scripts.pory"

# 60 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_SetReadyForScottScene::
# 61 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
# 62 "data/maps/SlateportCity/scripts.pory"
	getplayerxy VAR_0x8004, VAR_0x8005
# 63 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_0x8004, 30, SlateportCity_EventScript_MoveScottLeft
# 64 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_SCOTT, 23, 27
# 65 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_SCOTT, MOVEMENT_TYPE_FACE_RIGHT
# 66 "data/maps/SlateportCity/scripts.pory"
	return
# 67 "data/maps/SlateportCity/scripts.pory"

# 68 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_MoveScottLeft::
# 69 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_SCOTT, 22, 27
# 70 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_SCOTT, MOVEMENT_TYPE_FACE_RIGHT
# 71 "data/maps/SlateportCity/scripts.pory"
	return
# 72 "data/maps/SlateportCity/scripts.pory"

# 73 "data/maps/SlateportCity/scripts.pory"
SlateportCity_OnFrame:
# 74 "data/maps/SlateportCity/scripts.pory"
	map_script_2 VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE, 1, SlateportCity_EventScript_ScottScene
# 75 "data/maps/SlateportCity/scripts.pory"
	.2byte 0
# 76 "data/maps/SlateportCity/scripts.pory"

# 77 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ScottScene::
# 78 "data/maps/SlateportCity/scripts.pory"
	lockall
# 79 "data/maps/SlateportCity/scripts.pory"
	addobject LOCALID_SCOTT
# 80 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SlateportCity_Movement_PlayerFaceScott
# 81 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, SlateportCity_Movement_ScottApproachPlayer
# 82 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 83 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_YouDroveTeamAquaAway, MSGBOX_DEFAULT
# 84 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 85 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, Common_Movement_WalkInPlaceFasterLeft
# 86 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 87 "data/maps/SlateportCity/scripts.pory"
	delay 60
# 88 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_MaybeThisTrainer, MSGBOX_DEFAULT
# 89 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, Common_Movement_WalkInPlaceFasterRight
# 90 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 91 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_LetsRegisterEachOther, MSGBOX_DEFAULT
# 92 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 93 "data/maps/SlateportCity/scripts.pory"
	delay 30
# 94 "data/maps/SlateportCity/scripts.pory"
	playfanfare MUS_REGISTER_MATCH_CALL
# 95 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_RegisteredScott, MSGBOX_DEFAULT
# 96 "data/maps/SlateportCity/scripts.pory"
	waitfanfare
# 97 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 98 "data/maps/SlateportCity/scripts.pory"
	delay 30
# 99 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_ENABLE_SCOTT_MATCH_CALL
# 100 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_KeepEyeOnTrainersBeSeeingYou, MSGBOX_DEFAULT
# 101 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 102 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, SlateportCity_Movement_ScottExit
# 103 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 104 "data/maps/SlateportCity/scripts.pory"
	removeobject LOCALID_SCOTT
# 105 "data/maps/SlateportCity/scripts.pory"
	setobjectxyperm LOCALID_SCOTT, 10, 12
# 106 "data/maps/SlateportCity/scripts.pory"
	setobjectmovementtype LOCALID_SCOTT, MOVEMENT_TYPE_FACE_DOWN
# 107 "data/maps/SlateportCity/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 108 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE, 2
# 109 "data/maps/SlateportCity/scripts.pory"
	addvar VAR_SCOTT_STATE, 1
# 110 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 111 "data/maps/SlateportCity/scripts.pory"
	end
# 112 "data/maps/SlateportCity/scripts.pory"

# 113 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_PlayerFaceScott:
# 114 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 115 "data/maps/SlateportCity/scripts.pory"
	delay_8
# 116 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_left
# 117 "data/maps/SlateportCity/scripts.pory"
	step_end
# 118 "data/maps/SlateportCity/scripts.pory"

# 119 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_ScottApproachPlayer:
# 120 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 121 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 122 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 123 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 124 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 125 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 126 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 127 "data/maps/SlateportCity/scripts.pory"
	step_end
# 128 "data/maps/SlateportCity/scripts.pory"

# 129 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_ScottExit:
# 130 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 131 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 132 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 133 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 134 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 135 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 136 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 137 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 138 "data/maps/SlateportCity/scripts.pory"
	step_end
# 139 "data/maps/SlateportCity/scripts.pory"

# 140 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_CompGuy1::
# 141 "data/maps/SlateportCity/scripts.pory"
	lock
# 142 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 143 "data/maps/SlateportCity/scripts.pory"
	message SlateportCity_Text_CompGuy1SellWhatYouNeed
# 144 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 145 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_CompGuy1
# 146 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 147 "data/maps/SlateportCity/scripts.pory"
	release
# 148 "data/maps/SlateportCity/scripts.pory"
	end
# 149 "data/maps/SlateportCity/scripts.pory"

# 150 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 151 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_CompGuy1: @ Offensivve items
# 152 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CHOICE_BAND
# 153 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CHOICE_SPECS
# 154 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CHOICE_SCARF
# 155 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LIFE_ORB
# 156 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_FLAME_ORB
# 157 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TOXIC_ORB
# 158 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_THROAT_SPRAY
# 159 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LOADED_DICE
# 160 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_QUICK_CLAW
# 161 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_POWER_HERB
# 162 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_WHITE_HERB
# 163 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MENTAL_HERB
# 164 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MIRROR_HERB
# 165 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ROOM_SERVICE
# 166 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_BLUNDER_POLICY
# 167 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_IRON_BALL
# 168 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 169 "data/maps/SlateportCity/scripts.pory"
	release
# 170 "data/maps/SlateportCity/scripts.pory"
	end
# 171 "data/maps/SlateportCity/scripts.pory"

# 172 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_CompGuy2::
# 173 "data/maps/SlateportCity/scripts.pory"
	lock
# 174 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 175 "data/maps/SlateportCity/scripts.pory"
	message SlateportCity_Text_CompGuy2SellWhatYouNeed
# 176 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 177 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_CompGuy2
# 178 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 179 "data/maps/SlateportCity/scripts.pory"
	release
# 180 "data/maps/SlateportCity/scripts.pory"
	end
# 181 "data/maps/SlateportCity/scripts.pory"

# 182 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 183 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_CompGuy2: @ Defensive items
# 184 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_HEAVY_DUTY_BOOTS
# 185 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ASSAULT_VEST
# 186 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_EVIOLITE
# 187 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LEFTOVERS
# 188 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ROCKY_HELMET
# 189 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_FOCUS_SASH
# 190 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_FOCUS_BAND
# 191 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_AIR_BALLOON
# 192 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_WEAKNESS_POLICY
# 193 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_BRIGHT_POWDER
# 194 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PROTECTIVE_PADS
# 195 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PUNCHING_GLOVE
# 196 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ABILITY_SHIELD
# 197 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CLEAR_AMULET
# 198 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_COVERT_CLOAK
# 199 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 200 "data/maps/SlateportCity/scripts.pory"
	release
# 201 "data/maps/SlateportCity/scripts.pory"
	end
# 202 "data/maps/SlateportCity/scripts.pory"

# 203 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Cook::
# 204 "data/maps/SlateportCity/scripts.pory"
	lock
# 205 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 206 "data/maps/SlateportCity/scripts.pory"
	message SlateportCity_Text_NoveltiesAroundTheWorld
# 207 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 208 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_Cook
# 209 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 210 "data/maps/SlateportCity/scripts.pory"
	release
# 211 "data/maps/SlateportCity/scripts.pory"
	end
# 212 "data/maps/SlateportCity/scripts.pory"

# 213 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 214 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_Cook:
# 215 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PEWTER_CRUNCHIES
# 216 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_RAGE_CANDY_BAR
# 217 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LAVA_COOKIE
# 218 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_OLD_GATEAU
# 219 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CASTELIACONE
# 220 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LUMIOSE_GALETTE
# 221 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SHALOUR_SABLE
# 222 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_BIG_MALASADA
# 223 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 224 "data/maps/SlateportCity/scripts.pory"
	release
# 225 "data/maps/SlateportCity/scripts.pory"
	end
# 226 "data/maps/SlateportCity/scripts.pory"

# 227 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_OldWoman::
# 228 "data/maps/SlateportCity/scripts.pory"
	lock
# 229 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 230 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_OldWomanSternInterview
# 231 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HowTownIsBornAndGrows, MSGBOX_DEFAULT
# 232 "data/maps/SlateportCity/scripts.pory"
	release
# 233 "data/maps/SlateportCity/scripts.pory"
	end
# 234 "data/maps/SlateportCity/scripts.pory"

# 235 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_OldWomanSternInterview::
# 236 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_CaptSternBeingInterviewed, MSGBOX_DEFAULT
# 237 "data/maps/SlateportCity/scripts.pory"
	release
# 238 "data/maps/SlateportCity/scripts.pory"
	end
# 239 "data/maps/SlateportCity/scripts.pory"

# 240 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Girl::
# 241 "data/maps/SlateportCity/scripts.pory"
	lock
# 242 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 243 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_GirlSternInterview
# 244 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_RECEIVED_SECRET_POWER, SlateportCity_EventScript_GirlSecretBase
# 245 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SlateportWonderfulPlace, MSGBOX_DEFAULT
# 246 "data/maps/SlateportCity/scripts.pory"
	release
# 247 "data/maps/SlateportCity/scripts.pory"
	end
# 248 "data/maps/SlateportCity/scripts.pory"

# 249 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_GirlSternInterview::
# 250 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_InterviewerSoCool, MSGBOX_DEFAULT
# 251 "data/maps/SlateportCity/scripts.pory"
	release
# 252 "data/maps/SlateportCity/scripts.pory"
	end
# 253 "data/maps/SlateportCity/scripts.pory"

# 254 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_GirlSecretBase::
# 255 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BuyBricksSoDecorWontGetDirty, MSGBOX_DEFAULT
# 256 "data/maps/SlateportCity/scripts.pory"
	release
# 257 "data/maps/SlateportCity/scripts.pory"
	end
# 258 "data/maps/SlateportCity/scripts.pory"

# 259 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_RichBoy::
# 260 "data/maps/SlateportCity/scripts.pory"
	lock
# 261 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 262 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_RichBoySternInterview
# 263 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_GoingToCompeteInBattleTent, MSGBOX_DEFAULT
# 264 "data/maps/SlateportCity/scripts.pory"
	release
# 265 "data/maps/SlateportCity/scripts.pory"
	end
# 266 "data/maps/SlateportCity/scripts.pory"

# 267 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_RichBoySternInterview::
# 268 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternSaysDiscoveredSomething, MSGBOX_DEFAULT
# 269 "data/maps/SlateportCity/scripts.pory"
	release
# 270 "data/maps/SlateportCity/scripts.pory"
	end
# 271 "data/maps/SlateportCity/scripts.pory"

# 272 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_FatMan::
# 273 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_FatManSternInterview
# 274 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BushedHikingFromMauville, MSGBOX_NPC
# 275 "data/maps/SlateportCity/scripts.pory"
	end
# 276 "data/maps/SlateportCity/scripts.pory"

# 277 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_FatManSternInterview::
# 278 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_AmIOnTV, MSGBOX_SIGN
# 279 "data/maps/SlateportCity/scripts.pory"
	end
# 280 "data/maps/SlateportCity/scripts.pory"

# 281 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Man1::
# 282 "data/maps/SlateportCity/scripts.pory"
	lock
# 283 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 284 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_Man1SternInterview
# 285 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_EveryoneCallsHimCaptStern, MSGBOX_DEFAULT
# 286 "data/maps/SlateportCity/scripts.pory"
	release
# 287 "data/maps/SlateportCity/scripts.pory"
	end
# 288 "data/maps/SlateportCity/scripts.pory"

# 289 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Man1SternInterview::
# 290 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_CaptainsACelebrity, MSGBOX_DEFAULT
# 291 "data/maps/SlateportCity/scripts.pory"
	release
# 292 "data/maps/SlateportCity/scripts.pory"
	end
# 293 "data/maps/SlateportCity/scripts.pory"

# 294 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Woman1::
# 295 "data/maps/SlateportCity/scripts.pory"
	lock
# 296 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 297 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_DOCK_REJECTED_DEVON_GOODS, SlateportCity_EventScript_Woman1AquaGone
# 298 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhatsLongLineOverThere, MSGBOX_DEFAULT
# 299 "data/maps/SlateportCity/scripts.pory"
	release
# 300 "data/maps/SlateportCity/scripts.pory"
	end
# 301 "data/maps/SlateportCity/scripts.pory"

# 302 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Woman1AquaGone::
# 303 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_VisitedMuseumOften, MSGBOX_DEFAULT
# 304 "data/maps/SlateportCity/scripts.pory"
	release
# 305 "data/maps/SlateportCity/scripts.pory"
	end
# 306 "data/maps/SlateportCity/scripts.pory"

# 307 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_BattleTentSign::
# 308 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BattleTentSign, MSGBOX_SIGN
# 309 "data/maps/SlateportCity/scripts.pory"
	end
# 310 "data/maps/SlateportCity/scripts.pory"

# 311 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_SternsShipyardSign::
# 312 "data/maps/SlateportCity/scripts.pory"
	lockall
# 313 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_SYS_GAME_CLEAR, SlateportCity_EventScript_SternsShipyardFerryComplete
# 314 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_BADGE07_GET, SlateportCity_EventScript_SternsShipyardNearsCompletion
# 315 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternsShipyardWantedSign, MSGBOX_DEFAULT
# 316 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 317 "data/maps/SlateportCity/scripts.pory"
	end
# 318 "data/maps/SlateportCity/scripts.pory"

# 319 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_SternsShipyardNearsCompletion::
# 320 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternsShipyardNearsCompletion, MSGBOX_DEFAULT
# 321 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 322 "data/maps/SlateportCity/scripts.pory"
	end
# 323 "data/maps/SlateportCity/scripts.pory"

# 324 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_SternsShipyardFerryComplete::
# 325 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternsShipyardFerryComplete, MSGBOX_DEFAULT
# 326 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 327 "data/maps/SlateportCity/scripts.pory"
	end
# 328 "data/maps/SlateportCity/scripts.pory"

# 329 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_PokemonFanClubSign::
# 330 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_PokemonFanClubSign, MSGBOX_SIGN
# 331 "data/maps/SlateportCity/scripts.pory"
	end
# 332 "data/maps/SlateportCity/scripts.pory"

# 333 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_OceanicMuseumSign::
# 334 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_OceanicMuseumSign, MSGBOX_SIGN
# 335 "data/maps/SlateportCity/scripts.pory"
	end
# 336 "data/maps/SlateportCity/scripts.pory"

# 337 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_CitySign::
# 338 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_CitySign, MSGBOX_SIGN
# 339 "data/maps/SlateportCity/scripts.pory"
	end
# 340 "data/maps/SlateportCity/scripts.pory"

# 341 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_MarketSign::
# 342 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_MarketSign, MSGBOX_SIGN
# 343 "data/maps/SlateportCity/scripts.pory"
	end
# 344 "data/maps/SlateportCity/scripts.pory"

# 345 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_HarborSign::
# 346 "data/maps/SlateportCity/scripts.pory"
	lockall
# 347 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_SYS_GAME_CLEAR, SlateportCity_EventScript_HarborSignFerryComplete
# 348 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HarborFerryUnderConstruction, MSGBOX_DEFAULT
# 349 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 350 "data/maps/SlateportCity/scripts.pory"
	end
# 351 "data/maps/SlateportCity/scripts.pory"

# 352 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_HarborSignFerryComplete::
# 353 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HarborSign, MSGBOX_DEFAULT
# 354 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 355 "data/maps/SlateportCity/scripts.pory"
	end
# 356 "data/maps/SlateportCity/scripts.pory"

# 357 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_NameRatersHouseSign::
# 358 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_NameRatersHouseSign, MSGBOX_SIGN
# 359 "data/maps/SlateportCity/scripts.pory"
	end
# 360 "data/maps/SlateportCity/scripts.pory"

# 361 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Maniac::
# 362 "data/maps/SlateportCity/scripts.pory"
	lock
# 363 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 364 "data/maps/SlateportCity/scripts.pory"
	call_if_eq VAR_SLATEPORT_CITY_STATE, 1, SlateportCity_EventScript_ManiacSternInterview
# 365 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_GetNameRaterToHelpYou, MSGBOX_DEFAULT
# 366 "data/maps/SlateportCity/scripts.pory"
	release
# 367 "data/maps/SlateportCity/scripts.pory"
	end
# 368 "data/maps/SlateportCity/scripts.pory"

# 369 "data/maps/SlateportCity/scripts.pory"
@ Unclear if the text here was meant to be different, but its not
# 370 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ManiacSternInterview::
# 371 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_GetNameRaterToHelpYou, MSGBOX_DEFAULT
# 372 "data/maps/SlateportCity/scripts.pory"
	release
# 373 "data/maps/SlateportCity/scripts.pory"
	end
# 374 "data/maps/SlateportCity/scripts.pory"

# 375 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Woman2::
# 376 "data/maps/SlateportCity/scripts.pory"
	lock
# 377 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 378 "data/maps/SlateportCity/scripts.pory"
	dotimebasedevents
# 379 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_DAILY_HARBOR_MAIL_RECEIVED, SlateportCity_EventScriptWelcomeToSlateport
# 380 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WelcomeToSlateportMarket, MSGBOX_NPC
# 381 "data/maps/SlateportCity/scripts.pory"
	giveitem ITEM_HARBOR_MAIL
# 382 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_EnjoyYourStay, MSGBOX_NPC
# 383 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_DAILY_HARBOR_MAIL_RECEIVED
# 384 "data/maps/SlateportCity/scripts.pory"
	release
# 385 "data/maps/SlateportCity/scripts.pory"
	end
# 386 "data/maps/SlateportCity/scripts.pory"

# 387 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScriptWelcomeToSlateport:
# 388 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WelcomeToSlateportMarket2, MSGBOX_NPC
# 389 "data/maps/SlateportCity/scripts.pory"
	release
# 390 "data/maps/SlateportCity/scripts.pory"
	end
# 391 "data/maps/SlateportCity/scripts.pory"

# 392 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Sailor1::
# 393 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SeaIsSoWet, MSGBOX_NPC
# 394 "data/maps/SlateportCity/scripts.pory"
	end
# 395 "data/maps/SlateportCity/scripts.pory"

# 396 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Sailor2::
# 397 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SinkOldBoats, MSGBOX_NPC
# 398 "data/maps/SlateportCity/scripts.pory"
	end
# 399 "data/maps/SlateportCity/scripts.pory"

# 400 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_PokefanF::
# 401 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BuyTooMuch, MSGBOX_NPC
# 402 "data/maps/SlateportCity/scripts.pory"
	end
# 403 "data/maps/SlateportCity/scripts.pory"

# 404 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Man2::
# 405 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BattleTentBuiltRecently, MSGBOX_NPC
# 406 "data/maps/SlateportCity/scripts.pory"
	end
# 407 "data/maps/SlateportCity/scripts.pory"

# 408 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt1::
# 409 "data/maps/SlateportCity/scripts.pory"
	lock
# 410 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 411 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_QuitPushing, MSGBOX_DEFAULT
# 412 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 413 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_1, Common_Movement_FaceOriginalDirection
# 414 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 415 "data/maps/SlateportCity/scripts.pory"
	release
# 416 "data/maps/SlateportCity/scripts.pory"
	end
# 417 "data/maps/SlateportCity/scripts.pory"

# 418 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt2::
# 419 "data/maps/SlateportCity/scripts.pory"
	lock
# 420 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 421 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_AquaHasPolicy, MSGBOX_DEFAULT
# 422 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 423 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_2, Common_Movement_FaceOriginalDirection
# 424 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 425 "data/maps/SlateportCity/scripts.pory"
	release
# 426 "data/maps/SlateportCity/scripts.pory"
	end
# 427 "data/maps/SlateportCity/scripts.pory"

# 428 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt3::
# 429 "data/maps/SlateportCity/scripts.pory"
	lock
# 430 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 431 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BossIsBrilliant, MSGBOX_DEFAULT
# 432 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 433 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_3, Common_Movement_FaceOriginalDirection
# 434 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 435 "data/maps/SlateportCity/scripts.pory"
	release
# 436 "data/maps/SlateportCity/scripts.pory"
	end
# 437 "data/maps/SlateportCity/scripts.pory"

# 438 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt4::
# 439 "data/maps/SlateportCity/scripts.pory"
	lock
# 440 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 441 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhatsNewSchemeIWonder, MSGBOX_DEFAULT
# 442 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 443 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_4, Common_Movement_FaceOriginalDirection
# 444 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 445 "data/maps/SlateportCity/scripts.pory"
	release
# 446 "data/maps/SlateportCity/scripts.pory"
	end
# 447 "data/maps/SlateportCity/scripts.pory"

# 448 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt5::
# 449 "data/maps/SlateportCity/scripts.pory"
	lock
# 450 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 451 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ShouldTakeItAll, MSGBOX_DEFAULT
# 452 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 453 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_5, Common_Movement_FaceOriginalDirection
# 454 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 455 "data/maps/SlateportCity/scripts.pory"
	release
# 456 "data/maps/SlateportCity/scripts.pory"
	end
# 457 "data/maps/SlateportCity/scripts.pory"

# 458 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt6::
# 459 "data/maps/SlateportCity/scripts.pory"
	lock
# 460 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 461 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_DontButtIn, MSGBOX_DEFAULT
# 462 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 463 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_6, Common_Movement_FaceOriginalDirection
# 464 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 465 "data/maps/SlateportCity/scripts.pory"
	release
# 466 "data/maps/SlateportCity/scripts.pory"
	end
# 467 "data/maps/SlateportCity/scripts.pory"

# 468 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt7::
# 469 "data/maps/SlateportCity/scripts.pory"
	lock
# 470 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 471 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_RemindsMeOfLongLineForGames, MSGBOX_DEFAULT
# 472 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 473 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_7, Common_Movement_FaceOriginalDirection
# 474 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 475 "data/maps/SlateportCity/scripts.pory"
	release
# 476 "data/maps/SlateportCity/scripts.pory"
	end
# 477 "data/maps/SlateportCity/scripts.pory"

# 478 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt8::
# 479 "data/maps/SlateportCity/scripts.pory"
	lock
# 480 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 481 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhyAreWeLiningUp, MSGBOX_DEFAULT
# 482 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 483 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_8, Common_Movement_FaceOriginalDirection
# 484 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 485 "data/maps/SlateportCity/scripts.pory"
	release
# 486 "data/maps/SlateportCity/scripts.pory"
	end
# 487 "data/maps/SlateportCity/scripts.pory"

# 488 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt9::
# 489 "data/maps/SlateportCity/scripts.pory"
	lock
# 490 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 491 "data/maps/SlateportCity/scripts.pory"
	playse SE_PIN
# 492 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_ExclamationMark
# 493 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 494 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_Delay48
# 495 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 496 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhatDoYouWant, MSGBOX_DEFAULT
# 497 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 498 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_FaceOriginalDirection
# 499 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 500 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, SlateportCity_Movement_DelayAquaGrunt
# 501 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 502 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_FacePlayer
# 503 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 504 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_IllReadSignForYou, MSGBOX_DEFAULT
# 505 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 506 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_FaceOriginalDirection
# 507 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 508 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, SlateportCity_Movement_DelayAquaGrunt
# 509 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 510 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SaysSomethingLikeSeaIsEndless, MSGBOX_DEFAULT
# 511 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 512 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_FacePlayer
# 513 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 514 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, SlateportCity_Movement_DelayAquaGrunt
# 515 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 516 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_9, Common_Movement_FaceOriginalDirection
# 517 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 518 "data/maps/SlateportCity/scripts.pory"
	release
# 519 "data/maps/SlateportCity/scripts.pory"
	end
# 520 "data/maps/SlateportCity/scripts.pory"

# 521 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_DelayAquaGrunt:
# 522 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 523 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 524 "data/maps/SlateportCity/scripts.pory"
	step_end
# 525 "data/maps/SlateportCity/scripts.pory"

# 526 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt10::
# 527 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ShouldveBroughtMyGameBoy, MSGBOX_SIGN
# 528 "data/maps/SlateportCity/scripts.pory"
	end
# 529 "data/maps/SlateportCity/scripts.pory"

# 530 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_AquaGrunt11::
# 531 "data/maps/SlateportCity/scripts.pory"
	lock
# 532 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 533 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HotSpringsAfterOperation, MSGBOX_DEFAULT
# 534 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 535 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GRUNT_11, Common_Movement_FaceOriginalDirection
# 536 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 537 "data/maps/SlateportCity/scripts.pory"
	release
# 538 "data/maps/SlateportCity/scripts.pory"
	end
# 539 "data/maps/SlateportCity/scripts.pory"

# 540 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_EvoStonesClerk1::
# 541 "data/maps/SlateportCity/scripts.pory"
	lock
# 542 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 543 "data/maps/SlateportCity/scripts.pory"
	message gText_HowMayIServeYou
# 544 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 545 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_EvoStones1
# 546 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 547 "data/maps/SlateportCity/scripts.pory"
	release
# 548 "data/maps/SlateportCity/scripts.pory"
	end
# 549 "data/maps/SlateportCity/scripts.pory"

# 550 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 551 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_EvoStones1:
# 552 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 553 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_WATER_STONE
# 554 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 555 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 556 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ICE_STONE
# 557 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SUN_STONE
# 558 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MOON_STONE
# 559 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SHINY_STONE
# 560 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_DUSK_STONE
# 561 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_DAWN_STONE
# 562 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LINKING_CORD
# 563 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_EVERSTONE
# 564 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 565 "data/maps/SlateportCity/scripts.pory"
	release
# 566 "data/maps/SlateportCity/scripts.pory"
	end
# 567 "data/maps/SlateportCity/scripts.pory"

# 568 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_EvoStonesClerk2::
# 569 "data/maps/SlateportCity/scripts.pory"
	lock
# 570 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 571 "data/maps/SlateportCity/scripts.pory"
	message gText_HowMayIServeYou
# 572 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 573 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_EvoStones2
# 574 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 575 "data/maps/SlateportCity/scripts.pory"
	release
# 576 "data/maps/SlateportCity/scripts.pory"
	end
# 577 "data/maps/SlateportCity/scripts.pory"

# 578 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 579 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_EvoStones2:
# 580 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_OVAL_STONE
# 581 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_UPGRADE
# 582 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_DUBIOUS_DISC
# 583 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_KINGS_ROCK
# 584 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PRISM_SCALE
# 585 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PROTECTOR
# 586 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_ELECTIRIZER
# 587 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MAGMARIZER
# 588 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_RAZOR_CLAW
# 589 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_RAZOR_FANG
# 590 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_REAPER_CLOTH
# 591 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_DEEP_SEA_TOOTH
# 592 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_DEEP_SEA_SCALE
# 593 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SACHET
# 594 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_WHIPPED_DREAM
# 595 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SWEET_APPLE
# 596 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TART_APPLE
# 597 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CRACKED_POT
# 598 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_CHIPPED_POT
# 599 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_GALARICA_CUFF
# 600 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_GALARICA_WREATH
# 601 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_AUSPICIOUS_ARMOR
# 602 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MALICIOUS_ARMOR
# 603 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SCROLL_OF_DARKNESS
# 604 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SCROLL_OF_WATERS
# 605 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_BLACK_AUGURITE
# 606 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_PEAT_BLOCK
# 607 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_LEADERS_CREST
# 608 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SYRUPY_APPLE
# 609 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_UNREMARKABLE_TEACUP
# 610 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_MASTERPIECE_TEACUP
# 611 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_METAL_ALLOY
# 612 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_STEEL_ARMOR
# 613 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_GIMMIGHOUL_COIN
# 614 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_SYRUPY_APPLE
# 615 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 616 "data/maps/SlateportCity/scripts.pory"
	release
# 617 "data/maps/SlateportCity/scripts.pory"
	end
# 618 "data/maps/SlateportCity/scripts.pory"

# 619 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ComeBackWithSecretPower::
# 620 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_ComeBackWithSecretPower, MSGBOX_DEFAULT
# 621 "data/maps/SlateportCity/scripts.pory"
	release
# 622 "data/maps/SlateportCity/scripts.pory"
	end
# 623 "data/maps/SlateportCity/scripts.pory"

# 624 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_DecorClerk::
# 625 "data/maps/SlateportCity/scripts.pory"
	lock
# 626 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 627 "data/maps/SlateportCity/scripts.pory"
	goto_if_unset FLAG_RECEIVED_SECRET_POWER, SlateportCity_EventScript_ComeBackWithSecretPower
# 628 "data/maps/SlateportCity/scripts.pory"
	message gText_HowMayIServeYou
# 629 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 630 "data/maps/SlateportCity/scripts.pory"
	pokemartdecoration SlateportCity_PokemartDecor
# 631 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 632 "data/maps/SlateportCity/scripts.pory"
	release
# 633 "data/maps/SlateportCity/scripts.pory"
	end
# 634 "data/maps/SlateportCity/scripts.pory"

# 635 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 636 "data/maps/SlateportCity/scripts.pory"
SlateportCity_PokemartDecor:
# 637 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_RED_BRICK
# 638 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_BLUE_BRICK
# 639 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_YELLOW_BRICK
# 640 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_RED_BALLOON
# 641 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_BLUE_BALLOON
# 642 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_YELLOW_BALLOON
# 643 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_C_LOW_NOTE_MAT
# 644 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_D_NOTE_MAT
# 645 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_E_NOTE_MAT
# 646 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_F_NOTE_MAT
# 647 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_G_NOTE_MAT
# 648 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_A_NOTE_MAT
# 649 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_B_NOTE_MAT
# 650 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_C_HIGH_NOTE_MAT
# 651 "data/maps/SlateportCity/scripts.pory"
	.2byte DECOR_NONE
# 652 "data/maps/SlateportCity/scripts.pory"
	release
# 653 "data/maps/SlateportCity/scripts.pory"
	end
# 654 "data/maps/SlateportCity/scripts.pory"

# 655 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_PowerTMClerk::
# 656 "data/maps/SlateportCity/scripts.pory"
	lock
# 657 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 658 "data/maps/SlateportCity/scripts.pory"
	message gText_HowMayIServeYou
# 659 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 660 "data/maps/SlateportCity/scripts.pory"
	pokemart SlateportCity_Pokemart_PowerTMs
# 661 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 662 "data/maps/SlateportCity/scripts.pory"
	release
# 663 "data/maps/SlateportCity/scripts.pory"
	end
# 664 "data/maps/SlateportCity/scripts.pory"

# 665 "data/maps/SlateportCity/scripts.pory"
	.align 2
# 666 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Pokemart_PowerTMs:
# 667 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_PROTECT
# 668 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_SWORDS_DANCE
# 669 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_NASTY_PLOT
# 670 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_DRAGON_DANCE
# 671 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_SECRET_POWER
# 672 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_TM_NATURE_POWER
# 673 "data/maps/SlateportCity/scripts.pory"
	.2byte ITEM_NONE
# 674 "data/maps/SlateportCity/scripts.pory"
	release
# 675 "data/maps/SlateportCity/scripts.pory"
	end
# 676 "data/maps/SlateportCity/scripts.pory"

# 677 "data/maps/SlateportCity/scripts.pory"
@ Scene with Capt Sterns interview and Team Aqua announcing plans to steal Submarine
# 678 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_CaptStern::
# 679 "data/maps/SlateportCity/scripts.pory"
	lockall
# 680 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternMoveAheadWithExploration, MSGBOX_DEFAULT
# 681 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_GabbyWonderfulThanksForInterview, MSGBOX_DEFAULT
# 682 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 683 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GABBY, Common_Movement_WalkInPlaceFasterRight
# 684 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 685 "data/maps/SlateportCity/scripts.pory"
	delay 10
# 686 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_TY, Common_Movement_WalkInPlaceFasterDown
# 687 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 688 "data/maps/SlateportCity/scripts.pory"
	delay 25
# 689 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, SlateportCity_Movement_SternWatchGabbyAndTyExit
# 690 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SlateportCity_Movement_PlayerFaceStern
# 691 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_GABBY, SlateportCity_Movement_GabbyExit
# 692 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_TY, SlateportCity_Movement_TyExit
# 693 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 694 "data/maps/SlateportCity/scripts.pory"
	removeobject LOCALID_GABBY
# 695 "data/maps/SlateportCity/scripts.pory"
	removeobject LOCALID_TY
# 696 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternWhewFirstInterview, MSGBOX_DEFAULT
# 697 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, Common_Movement_WalkInPlaceFasterUp
# 698 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 699 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_OhPlayerWeMadeDiscovery, MSGBOX_DEFAULT
# 700 "data/maps/SlateportCity/scripts.pory"
	playbgm MUS_ENCOUNTER_AQUA, FALSE
# 701 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_AquaWillAssumeControlOfSubmarine, MSGBOX_DEFAULT
# 702 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_COOK, Common_Movement_WalkInPlaceFasterLeft
# 703 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_FAT_MAN, Common_Movement_WalkInPlaceFasterLeft
# 704 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_OLD_WOMAN, SlateportCity_Movement_OldWomanConcern
# 705 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_RICH_BOY, Common_Movement_QuestionMark
# 706 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_MAN_1, SlateportCity_Movement_ManConcern
# 707 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 708 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, Common_Movement_WalkInPlaceFasterDown
# 709 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 710 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternWhatWasAllThat, MSGBOX_DEFAULT
# 711 "data/maps/SlateportCity/scripts.pory"
	playse SE_PIN
# 712 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, Common_Movement_ExclamationMark
# 713 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 714 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, Common_Movement_Delay48
# 715 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 716 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, Common_Movement_WalkInPlaceFasterUp
# 717 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 718 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_FromHarborTryingToTakeSub, MSGBOX_DEFAULT
# 719 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_PleaseComeWithMe, MSGBOX_DEFAULT
# 720 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 721 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_CAPT_STERN, SlateportCity_Movement_SternEnterHarbor
# 722 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SlateportCity_Movement_PlayerEnterHarbor
# 723 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 724 "data/maps/SlateportCity/scripts.pory"
	removeobject LOCALID_CAPT_STERN
# 725 "data/maps/SlateportCity/scripts.pory"
	clearflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN
# 726 "data/maps/SlateportCity/scripts.pory"
	clearflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW
# 727 "data/maps/SlateportCity/scripts.pory"
	clearflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT
# 728 "data/maps/SlateportCity/scripts.pory"
	clearflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE
# 729 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_SLATEPORT_CITY_STATE, 2
# 730 "data/maps/SlateportCity/scripts.pory"
	warp MAP_SLATEPORT_CITY_HARBOR, 11, 14
# 731 "data/maps/SlateportCity/scripts.pory"
	waitstate
# 732 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 733 "data/maps/SlateportCity/scripts.pory"
	end
# 734 "data/maps/SlateportCity/scripts.pory"

# 735 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_OldWomanConcern:
# 736 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 737 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 738 "data/maps/SlateportCity/scripts.pory"
	emote_question_mark
# 739 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_right
# 740 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 741 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 742 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_left
# 743 "data/maps/SlateportCity/scripts.pory"
	step_end
# 744 "data/maps/SlateportCity/scripts.pory"

# 745 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_ManConcern:
# 746 "data/maps/SlateportCity/scripts.pory"
	emote_question_mark
# 747 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_up
# 748 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 749 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_down
# 750 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 751 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 752 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_left
# 753 "data/maps/SlateportCity/scripts.pory"
	step_end
# 754 "data/maps/SlateportCity/scripts.pory"

# 755 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_GabbyExit:
# 756 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 757 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 758 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 759 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 760 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 761 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 762 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 763 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 764 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 765 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 766 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 767 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 768 "data/maps/SlateportCity/scripts.pory"
	step_end
# 769 "data/maps/SlateportCity/scripts.pory"

# 770 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_TyExit:
# 771 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 772 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 773 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 774 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 775 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 776 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 777 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 778 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 779 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 780 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 781 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 782 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 783 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 784 "data/maps/SlateportCity/scripts.pory"
	step_end
# 785 "data/maps/SlateportCity/scripts.pory"

# 786 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_Unused:
# 787 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 788 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_up
# 789 "data/maps/SlateportCity/scripts.pory"
	step_end
# 790 "data/maps/SlateportCity/scripts.pory"

# 791 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_SternEnterHarbor:
# 792 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 793 "data/maps/SlateportCity/scripts.pory"
	walk_up
# 794 "data/maps/SlateportCity/scripts.pory"
	walk_up
# 795 "data/maps/SlateportCity/scripts.pory"
	set_invisible
# 796 "data/maps/SlateportCity/scripts.pory"
	step_end
# 797 "data/maps/SlateportCity/scripts.pory"

# 798 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_SternWatchGabbyAndTyExit:
# 799 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 800 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 801 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 802 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 803 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 804 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 805 "data/maps/SlateportCity/scripts.pory"
	walk_left
# 806 "data/maps/SlateportCity/scripts.pory"
	step_end
# 807 "data/maps/SlateportCity/scripts.pory"

# 808 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_PlayerEnterHarbor:
# 809 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_right
# 810 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 811 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 812 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 813 "data/maps/SlateportCity/scripts.pory"
	walk_up
# 814 "data/maps/SlateportCity/scripts.pory"
	step_end
# 815 "data/maps/SlateportCity/scripts.pory"

# 816 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_PlayerFaceStern:
# 817 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 818 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 819 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 820 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 821 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 822 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 823 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 824 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_down
# 825 "data/maps/SlateportCity/scripts.pory"
	step_end
# 826 "data/maps/SlateportCity/scripts.pory"

# 827 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Ty::
# 828 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BigSmileForCamera, MSGBOX_SIGN
# 829 "data/maps/SlateportCity/scripts.pory"
	end
# 830 "data/maps/SlateportCity/scripts.pory"

# 831 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Gabby::
# 832 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_MostInvaluableExperience, MSGBOX_SIGN
# 833 "data/maps/SlateportCity/scripts.pory"
	end
# 834 "data/maps/SlateportCity/scripts.pory"

# 835 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Man3::
# 836 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WonderIfLighthouseStartlesPokemon, MSGBOX_NPC
# 837 "data/maps/SlateportCity/scripts.pory"
	end
# 838 "data/maps/SlateportCity/scripts.pory"

# 839 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_BerryPowderClerk::
# 840 "data/maps/SlateportCity/scripts.pory"
	lock
# 841 "data/maps/SlateportCity/scripts.pory"
	faceplayer
# 842 "data/maps/SlateportCity/scripts.pory"
	goto_if_set FLAG_RECEIVED_POWDER_JAR, SlateportCity_EventScript_ReceivedPowderJar
# 843 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ExplainBerries, MSGBOX_DEFAULT
# 844 "data/maps/SlateportCity/scripts.pory"
	giveitem ITEM_POWDER_JAR
# 845 "data/maps/SlateportCity/scripts.pory"
	setflag FLAG_RECEIVED_POWDER_JAR
# 846 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ExplainBerryPowder, MSGBOX_DEFAULT
# 847 "data/maps/SlateportCity/scripts.pory"
	release
# 848 "data/maps/SlateportCity/scripts.pory"
	end
# 849 "data/maps/SlateportCity/scripts.pory"

# 850 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ReceivedPowderJar::
# 851 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8004, 1
# 852 "data/maps/SlateportCity/scripts.pory"
	specialvar VAR_RESULT, HasEnoughBerryPowder
# 853 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, SlateportCity_EventScript_ExplainBerryPowder
# 854 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BroughtMeSomeBerryPowder, MSGBOX_DEFAULT
# 855 "data/maps/SlateportCity/scripts.pory"
	special DisplayBerryPowderVendorMenu
# 856 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_ChooseBerryPowderItem
# 857 "data/maps/SlateportCity/scripts.pory"
	end
# 858 "data/maps/SlateportCity/scripts.pory"

# 859 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ExplainBerryPowder::
# 860 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ExplainBerryPowder, MSGBOX_DEFAULT
# 861 "data/maps/SlateportCity/scripts.pory"
	release
# 862 "data/maps/SlateportCity/scripts.pory"
	end
# 863 "data/maps/SlateportCity/scripts.pory"

# 864 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ChooseBerryPowderItem::
# 865 "data/maps/SlateportCity/scripts.pory"
	message SlateportCity_Text_ExchangeWhatWithIt
# 866 "data/maps/SlateportCity/scripts.pory"
	waitmessage
# 867 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8004, SCROLL_MULTI_BERRY_POWDER_VENDOR
# 868 "data/maps/SlateportCity/scripts.pory"
	special ShowScrollableMultichoice
# 869 "data/maps/SlateportCity/scripts.pory"
	waitstate
# 870 "data/maps/SlateportCity/scripts.pory"
	switch VAR_RESULT
# 871 "data/maps/SlateportCity/scripts.pory"
	case 0, SlateportCity_EventScript_EnergyPowder
# 872 "data/maps/SlateportCity/scripts.pory"
	case 1, SlateportCity_EventScript_EnergyRoot
# 873 "data/maps/SlateportCity/scripts.pory"
	case 2, SlateportCity_EventScript_HealPowder
# 874 "data/maps/SlateportCity/scripts.pory"
	case 3, SlateportCity_EventScript_RevivalHerb
# 875 "data/maps/SlateportCity/scripts.pory"
	case 4, SlateportCity_EventScript_Protein
# 876 "data/maps/SlateportCity/scripts.pory"
	case 5, SlateportCity_EventScript_Iron
# 877 "data/maps/SlateportCity/scripts.pory"
	case 6, SlateportCity_EventScript_Carbos
# 878 "data/maps/SlateportCity/scripts.pory"
	case 7, SlateportCity_EventScript_Calcium
# 879 "data/maps/SlateportCity/scripts.pory"
	case 8, SlateportCity_EventScript_Zinc
# 880 "data/maps/SlateportCity/scripts.pory"
	case 9, SlateportCity_EventScript_HPUp
# 881 "data/maps/SlateportCity/scripts.pory"
	case 10, SlateportCity_EventScript_PPUp
# 882 "data/maps/SlateportCity/scripts.pory"
	case 11, SlateportCity_EventScript_CancelPowderItemSelect
# 883 "data/maps/SlateportCity/scripts.pory"
	case MULTI_B_PRESSED, SlateportCity_EventScript_CancelPowderItemSelect
# 884 "data/maps/SlateportCity/scripts.pory"
	end
# 885 "data/maps/SlateportCity/scripts.pory"

# 886 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_EnergyPowder::
# 887 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_ENERGY_POWDER
# 888 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_ENERGY_POWDER
# 889 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 50
# 890 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 891 "data/maps/SlateportCity/scripts.pory"
	end
# 892 "data/maps/SlateportCity/scripts.pory"

# 893 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_EnergyRoot::
# 894 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_ENERGY_ROOT
# 895 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_ENERGY_ROOT
# 896 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 80
# 897 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 898 "data/maps/SlateportCity/scripts.pory"
	end
# 899 "data/maps/SlateportCity/scripts.pory"

# 900 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_HealPowder::
# 901 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_HEAL_POWDER
# 902 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_HEAL_POWDER
# 903 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 50
# 904 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 905 "data/maps/SlateportCity/scripts.pory"
	end
# 906 "data/maps/SlateportCity/scripts.pory"

# 907 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_RevivalHerb::
# 908 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_REVIVAL_HERB
# 909 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_REVIVAL_HERB
# 910 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 300
# 911 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 912 "data/maps/SlateportCity/scripts.pory"
	end
# 913 "data/maps/SlateportCity/scripts.pory"

# 914 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Protein::
# 915 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_PROTEIN
# 916 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_PROTEIN
# 917 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 918 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 919 "data/maps/SlateportCity/scripts.pory"
	end
# 920 "data/maps/SlateportCity/scripts.pory"

# 921 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Iron::
# 922 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_IRON
# 923 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_IRON
# 924 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 925 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 926 "data/maps/SlateportCity/scripts.pory"
	end
# 927 "data/maps/SlateportCity/scripts.pory"

# 928 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Carbos::
# 929 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_CARBOS
# 930 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_CARBOS
# 931 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 932 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 933 "data/maps/SlateportCity/scripts.pory"
	end
# 934 "data/maps/SlateportCity/scripts.pory"

# 935 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Calcium::
# 936 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_CALCIUM
# 937 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_CALCIUM
# 938 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 939 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 940 "data/maps/SlateportCity/scripts.pory"
	end
# 941 "data/maps/SlateportCity/scripts.pory"

# 942 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_Zinc::
# 943 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_ZINC
# 944 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_ZINC
# 945 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 946 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 947 "data/maps/SlateportCity/scripts.pory"
	end
# 948 "data/maps/SlateportCity/scripts.pory"

# 949 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_HPUp::
# 950 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_HP_UP
# 951 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_HP_UP
# 952 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 1000
# 953 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 954 "data/maps/SlateportCity/scripts.pory"
	end
# 955 "data/maps/SlateportCity/scripts.pory"

# 956 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_PPUp::
# 957 "data/maps/SlateportCity/scripts.pory"
	bufferitemname STR_VAR_1, ITEM_PP_UP
# 958 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8008, ITEM_PP_UP
# 959 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_0x8009, 3000
# 960 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_TryBuyBerryPowderItem
# 961 "data/maps/SlateportCity/scripts.pory"
	end
# 962 "data/maps/SlateportCity/scripts.pory"

# 963 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_CancelPowderItemSelect::
# 964 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ComeBackToTradeBerryPowder, MSGBOX_DEFAULT
# 965 "data/maps/SlateportCity/scripts.pory"
	special RemoveBerryPowderVendorMenu
# 966 "data/maps/SlateportCity/scripts.pory"
	release
# 967 "data/maps/SlateportCity/scripts.pory"
	end
# 968 "data/maps/SlateportCity/scripts.pory"

# 969 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_TryBuyBerryPowderItem::
# 970 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ExchangeBerryPowderForItem, MSGBOX_YESNO
# 971 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_RESULT, NO, SlateportCity_EventScript_ChooseBerryPowderItem
# 972 "data/maps/SlateportCity/scripts.pory"
	copyvar VAR_0x8004, VAR_0x8009
# 973 "data/maps/SlateportCity/scripts.pory"
	specialvar VAR_RESULT, HasEnoughBerryPowder
# 974 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, SlateportCity_EventScript_NotEnoughBerryPowder
# 975 "data/maps/SlateportCity/scripts.pory"
	giveitem VAR_0x8008
# 976 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, SlateportCity_EventScript_NoRoomForBerryPowderItem
# 977 "data/maps/SlateportCity/scripts.pory"
	copyvar VAR_0x8004, VAR_0x8009
# 978 "data/maps/SlateportCity/scripts.pory"
	special TakeBerryPowder
# 979 "data/maps/SlateportCity/scripts.pory"
	special PrintPlayerBerryPowderAmount
# 980 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_FineBerryPowderTradeSomethingElse, MSGBOX_YESNO
# 981 "data/maps/SlateportCity/scripts.pory"
	goto_if_eq VAR_RESULT, YES, SlateportCity_EventScript_ChooseBerryPowderItem
# 982 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhenYouGetMoreBringItToMe, MSGBOX_DEFAULT
# 983 "data/maps/SlateportCity/scripts.pory"
	special RemoveBerryPowderVendorMenu
# 984 "data/maps/SlateportCity/scripts.pory"
	release
# 985 "data/maps/SlateportCity/scripts.pory"
	end
# 986 "data/maps/SlateportCity/scripts.pory"

# 987 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_NoRoomForBerryPowderItem::
# 988 "data/maps/SlateportCity/scripts.pory"
	msgbox gText_TheBagIsFull, MSGBOX_DEFAULT
# 989 "data/maps/SlateportCity/scripts.pory"
	special RemoveBerryPowderVendorMenu
# 990 "data/maps/SlateportCity/scripts.pory"
	release
# 991 "data/maps/SlateportCity/scripts.pory"
	end
# 992 "data/maps/SlateportCity/scripts.pory"

# 993 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_NotEnoughBerryPowder::
# 994 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_DontHaveEnoughBerryPowder, MSGBOX_DEFAULT
# 995 "data/maps/SlateportCity/scripts.pory"
	goto SlateportCity_EventScript_ChooseBerryPowderItem
# 996 "data/maps/SlateportCity/scripts.pory"
	end
# 997 "data/maps/SlateportCity/scripts.pory"

# 998 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_ScottBattleTentScene::
# 999 "data/maps/SlateportCity/scripts.pory"
	lockall
# 1000 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceUp
# 1001 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 1002 "data/maps/SlateportCity/scripts.pory"
	opendoor 10, 12
# 1003 "data/maps/SlateportCity/scripts.pory"
	waitdooranim
# 1004 "data/maps/SlateportCity/scripts.pory"
	addobject LOCALID_SCOTT
# 1005 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SlateportCity_Movement_PushPlayerDown
# 1006 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, SlateportCity_Movement_ScottExitBattleTent
# 1007 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 1008 "data/maps/SlateportCity/scripts.pory"
	closedoor 10, 12
# 1009 "data/maps/SlateportCity/scripts.pory"
	waitdooranim
# 1010 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_TakingBattleTentChallenge, MSGBOX_DEFAULT
# 1011 "data/maps/SlateportCity/scripts.pory"
	closemessage
# 1012 "data/maps/SlateportCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SlateportCity_Movement_PlayerWatchScottExit
# 1013 "data/maps/SlateportCity/scripts.pory"
	applymovement LOCALID_SCOTT, SlateportCity_Movement_ScottExitAfterBattleTent
# 1014 "data/maps/SlateportCity/scripts.pory"
	waitmovement 0
# 1015 "data/maps/SlateportCity/scripts.pory"
	removeobject LOCALID_SCOTT
# 1016 "data/maps/SlateportCity/scripts.pory"
	addvar VAR_SCOTT_STATE, 1
# 1017 "data/maps/SlateportCity/scripts.pory"
	setvar VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE, 3
# 1018 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 1019 "data/maps/SlateportCity/scripts.pory"
	end
# 1020 "data/maps/SlateportCity/scripts.pory"

# 1021 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_PushPlayerDown:
# 1022 "data/maps/SlateportCity/scripts.pory"
	lock_facing_direction
# 1023 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 1024 "data/maps/SlateportCity/scripts.pory"
	unlock_facing_direction
# 1025 "data/maps/SlateportCity/scripts.pory"
	step_end
# 1026 "data/maps/SlateportCity/scripts.pory"

# 1027 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_PlayerWatchScottExit:
# 1028 "data/maps/SlateportCity/scripts.pory"
	delay_16
# 1029 "data/maps/SlateportCity/scripts.pory"
	walk_in_place_faster_right
# 1030 "data/maps/SlateportCity/scripts.pory"
	step_end
# 1031 "data/maps/SlateportCity/scripts.pory"

# 1032 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_ScottExitBattleTent:
# 1033 "data/maps/SlateportCity/scripts.pory"
	delay_8
# 1034 "data/maps/SlateportCity/scripts.pory"
	walk_down
# 1035 "data/maps/SlateportCity/scripts.pory"
	step_end
# 1036 "data/maps/SlateportCity/scripts.pory"

# 1037 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Movement_ScottExitAfterBattleTent:
# 1038 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1039 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1040 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1041 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1042 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1043 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1044 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1045 "data/maps/SlateportCity/scripts.pory"
	walk_right
# 1046 "data/maps/SlateportCity/scripts.pory"
	step_end
# 1047 "data/maps/SlateportCity/scripts.pory"

# 1048 "data/maps/SlateportCity/scripts.pory"
SlateportCity_EventScript_BerryCrushRankingsSign::
# 1049 "data/maps/SlateportCity/scripts.pory"
	lockall
# 1050 "data/maps/SlateportCity/scripts.pory"
	special ShowBerryCrushRankings
# 1051 "data/maps/SlateportCity/scripts.pory"
	waitstate
# 1052 "data/maps/SlateportCity/scripts.pory"
	releaseall
# 1053 "data/maps/SlateportCity/scripts.pory"
	end
# 1054 "data/maps/SlateportCity/scripts.pory"

# 1055 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_CompGuy1SellWhatYouNeed:
# 1056 "data/maps/SlateportCity/scripts.pory"
	.string "Hello! I'm Wolfey!\n"
# 1057 "data/maps/SlateportCity/scripts.pory"
	.string "The competitive guy!\p"
# 1058 "data/maps/SlateportCity/scripts.pory"
	.string "You in need of any items?$"
# 1059 "data/maps/SlateportCity/scripts.pory"

# 1060 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_CompGuy2SellWhatYouNeed:
# 1061 "data/maps/SlateportCity/scripts.pory"
	.string "Hi, I'm Ray!\n"
# 1062 "data/maps/SlateportCity/scripts.pory"
	.string "The older, and wiser, comepetitive\l"
# 1063 "data/maps/SlateportCity/scripts.pory"
	.string "guru!\p"
# 1064 "data/maps/SlateportCity/scripts.pory"
	.string "I've got some great items you'd be\n"
# 1065 "data/maps/SlateportCity/scripts.pory"
	.string "interested in.$"
# 1066 "data/maps/SlateportCity/scripts.pory"

# 1067 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_GoForItLittleHarder:
# 1068 "data/maps/SlateportCity/scripts.pory"
	.string "You have to go for it a little harder.\p"
# 1069 "data/maps/SlateportCity/scripts.pory"
	.string "If you do, I'll give your Pokémon\n"
# 1070 "data/maps/SlateportCity/scripts.pory"
	.string "something nice.$"
# 1071 "data/maps/SlateportCity/scripts.pory"

# 1072 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_EffortRibbonLooksGoodOnIt:
# 1073 "data/maps/SlateportCity/scripts.pory"
	.string "Oh! Your {STR_VAR_1}, that Effort\n"
# 1074 "data/maps/SlateportCity/scripts.pory"
	.string "Ribbon looks good on it!$"
# 1075 "data/maps/SlateportCity/scripts.pory"

# 1076 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WonderIfLighthouseStartlesPokemon:
# 1077 "data/maps/SlateportCity/scripts.pory"
	.string "The light of the lighthouse reaches\n"
# 1078 "data/maps/SlateportCity/scripts.pory"
	.string "dozens of miles away.\p"
# 1079 "data/maps/SlateportCity/scripts.pory"
	.string "I wonder if it doesn't startle Pokémon\n"
# 1080 "data/maps/SlateportCity/scripts.pory"
	.string "in the sea.$"
# 1081 "data/maps/SlateportCity/scripts.pory"

# 1082 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SeaweedFullOfLife:
# 1083 "data/maps/SlateportCity/scripts.pory"
	.string "Ooh, look at this!\p"
# 1084 "data/maps/SlateportCity/scripts.pory"
	.string "The seaweed you can get around these\n"
# 1085 "data/maps/SlateportCity/scripts.pory"
	.string "parts is fresh and full of life.\p"
# 1086 "data/maps/SlateportCity/scripts.pory"
	.string "Why, it looks like it can even rear up\n"
# 1087 "data/maps/SlateportCity/scripts.pory"
	.string "and attack!$"
# 1088 "data/maps/SlateportCity/scripts.pory"

# 1089 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_HowTownIsBornAndGrows:
# 1090 "data/maps/SlateportCity/scripts.pory"
	.string "Where the water is clean, the fruits\n"
# 1091 "data/maps/SlateportCity/scripts.pory"
	.string "of bountiful harvest gather.\p"
# 1092 "data/maps/SlateportCity/scripts.pory"
	.string "And where people gather, a market\n"
# 1093 "data/maps/SlateportCity/scripts.pory"
	.string "soon starts.\p"
# 1094 "data/maps/SlateportCity/scripts.pory"
	.string "That is how a town is born and grows.$"
# 1095 "data/maps/SlateportCity/scripts.pory"

# 1096 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SlateportWonderfulPlace:
# 1097 "data/maps/SlateportCity/scripts.pory"
	.string "Shopping where you can breathe the\n"
# 1098 "data/maps/SlateportCity/scripts.pory"
	.string "scent of the ocean…\p"
# 1099 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport is such a wonderful place!$"
# 1100 "data/maps/SlateportCity/scripts.pory"

# 1101 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BuyBricksSoDecorWontGetDirty:
# 1102 "data/maps/SlateportCity/scripts.pory"
	.string "If you put Dolls or Cushions on\n"
# 1103 "data/maps/SlateportCity/scripts.pory"
	.string "the floor, they'll get dirty.\p"
# 1104 "data/maps/SlateportCity/scripts.pory"
	.string "I'm going to buy some Bricks so my\n"
# 1105 "data/maps/SlateportCity/scripts.pory"
	.string "Dolls and Cushions won't get dirty\l"
# 1106 "data/maps/SlateportCity/scripts.pory"
	.string "when I leave them out.$"
# 1107 "data/maps/SlateportCity/scripts.pory"

# 1108 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_GoingToCompeteInBattleTent:
# 1109 "data/maps/SlateportCity/scripts.pory"
	.string "Wroooar! I'm going to compete in\n"
# 1110 "data/maps/SlateportCity/scripts.pory"
	.string "the Battle Tent, too!\p"
# 1111 "data/maps/SlateportCity/scripts.pory"
	.string "But before that, I need to catch\n"
# 1112 "data/maps/SlateportCity/scripts.pory"
	.string "some Pokémon!$"
# 1113 "data/maps/SlateportCity/scripts.pory"

# 1114 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BushedHikingFromMauville:
# 1115 "data/maps/SlateportCity/scripts.pory"
	.string "Whew… I'm just bushed…\p"
# 1116 "data/maps/SlateportCity/scripts.pory"
	.string "I hiked over from Mauville City.\n"
# 1117 "data/maps/SlateportCity/scripts.pory"
	.string "But, boy, this city's huge.\p"
# 1118 "data/maps/SlateportCity/scripts.pory"
	.string "If I'd known this, I would've ridden\n"
# 1119 "data/maps/SlateportCity/scripts.pory"
	.string "my Bike here.$"
# 1120 "data/maps/SlateportCity/scripts.pory"

# 1121 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_EveryoneCallsHimCaptStern:
# 1122 "data/maps/SlateportCity/scripts.pory"
	.string "Stern, the fellow who built the\n"
# 1123 "data/maps/SlateportCity/scripts.pory"
	.string "Museum, also happens to be the leader\l"
# 1124 "data/maps/SlateportCity/scripts.pory"
	.string "of an undersea exploration team.\p"
# 1125 "data/maps/SlateportCity/scripts.pory"
	.string "So, everyone calls him Capt. Stern.$"
# 1126 "data/maps/SlateportCity/scripts.pory"

# 1127 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WhatsLongLineOverThere:
# 1128 "data/maps/SlateportCity/scripts.pory"
	.string "What is that over there?\n"
# 1129 "data/maps/SlateportCity/scripts.pory"
	.string "That long line…$"
# 1130 "data/maps/SlateportCity/scripts.pory"

# 1131 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_VisitedMuseumOften:
# 1132 "data/maps/SlateportCity/scripts.pory"
	.string "When I was a child, I visited\n"
# 1133 "data/maps/SlateportCity/scripts.pory"
	.string "the Museum often.\p"
# 1134 "data/maps/SlateportCity/scripts.pory"
	.string "I used to dream about the mysteries of\n"
# 1135 "data/maps/SlateportCity/scripts.pory"
	.string "the sea after seeing the exhibits.$"
# 1136 "data/maps/SlateportCity/scripts.pory"

# 1137 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_QuitPushing:
# 1138 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, there! Quit pushing!\n"
# 1139 "data/maps/SlateportCity/scripts.pory"
	.string "This is the line, can't you see?$"
# 1140 "data/maps/SlateportCity/scripts.pory"

# 1141 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_AquaHasPolicy:
# 1142 "data/maps/SlateportCity/scripts.pory"
	.string "Team Aqua has a policy of\n"
# 1143 "data/maps/SlateportCity/scripts.pory"
	.string "assembling and dispersing at\l"
# 1144 "data/maps/SlateportCity/scripts.pory"
	.string "the operation site.$"
# 1145 "data/maps/SlateportCity/scripts.pory"

# 1146 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BossIsBrilliant:
# 1147 "data/maps/SlateportCity/scripts.pory"
	.string "Our Boss is brilliant.\p"
# 1148 "data/maps/SlateportCity/scripts.pory"
	.string "What would he want to do with\n"
# 1149 "data/maps/SlateportCity/scripts.pory"
	.string "a Museum now?$"
# 1150 "data/maps/SlateportCity/scripts.pory"

# 1151 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WhatsNewSchemeIWonder:
# 1152 "data/maps/SlateportCity/scripts.pory"
	.string "What's the new scheme, I wonder?\p"
# 1153 "data/maps/SlateportCity/scripts.pory"
	.string "Our Boss is scary when he's mad, so\n"
# 1154 "data/maps/SlateportCity/scripts.pory"
	.string "I'd better not screw things up…$"
# 1155 "data/maps/SlateportCity/scripts.pory"

# 1156 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ShouldTakeItAll:
# 1157 "data/maps/SlateportCity/scripts.pory"
	.string "If there's something we need in\n"
# 1158 "data/maps/SlateportCity/scripts.pory"
	.string "the Museum, we should take it all!$"
# 1159 "data/maps/SlateportCity/scripts.pory"

# 1160 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_DontButtIn:
# 1161 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, you there!\n"
# 1162 "data/maps/SlateportCity/scripts.pory"
	.string "Don't butt in!$"
# 1163 "data/maps/SlateportCity/scripts.pory"

# 1164 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_RemindsMeOfLongLineForGames:
# 1165 "data/maps/SlateportCity/scripts.pory"
	.string "A long line, huh?\p"
# 1166 "data/maps/SlateportCity/scripts.pory"
	.string "It reminds me of the times I lined up to\n"
# 1167 "data/maps/SlateportCity/scripts.pory"
	.string "buy smash-hit games…$"
# 1168 "data/maps/SlateportCity/scripts.pory"

# 1169 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WhyAreWeLiningUp:
# 1170 "data/maps/SlateportCity/scripts.pory"
	.string "Why are we even lining up and paying?\n"
# 1171 "data/maps/SlateportCity/scripts.pory"
	.string "We should just march in!$"
# 1172 "data/maps/SlateportCity/scripts.pory"

# 1173 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WhatDoYouWant:
# 1174 "data/maps/SlateportCity/scripts.pory"
	.string "What?\n"
# 1175 "data/maps/SlateportCity/scripts.pory"
	.string "What do you want?$"
# 1176 "data/maps/SlateportCity/scripts.pory"

# 1177 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_IllReadSignForYou:
# 1178 "data/maps/SlateportCity/scripts.pory"
	.string "You want to read this sign?\n"
# 1179 "data/maps/SlateportCity/scripts.pory"
	.string "I'll read it for you!$"
# 1180 "data/maps/SlateportCity/scripts.pory"

# 1181 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SaysSomethingLikeSeaIsEndless:
# 1182 "data/maps/SlateportCity/scripts.pory"
	.string "Let's see…\p"
# 1183 "data/maps/SlateportCity/scripts.pory"
	.string "Um… I think it says something like\n"
# 1184 "data/maps/SlateportCity/scripts.pory"
	.string "“the life in the sea is endless.”\p"
# 1185 "data/maps/SlateportCity/scripts.pory"
	.string "Yup, I'm pretty sure that's what\n"
# 1186 "data/maps/SlateportCity/scripts.pory"
	.string "it says.$"
# 1187 "data/maps/SlateportCity/scripts.pory"

# 1188 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ShouldveBroughtMyGameBoy:
# 1189 "data/maps/SlateportCity/scripts.pory"
	.string "Grumble…\p"
# 1190 "data/maps/SlateportCity/scripts.pory"
	.string "I should've brought my Game Boy\n"
# 1191 "data/maps/SlateportCity/scripts.pory"
	.string "Advance so I wouldn't get bored in line…\p"
# 1192 "data/maps/SlateportCity/scripts.pory"
	.string "Grumble…$"
# 1193 "data/maps/SlateportCity/scripts.pory"

# 1194 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_HotSpringsAfterOperation:
# 1195 "data/maps/SlateportCity/scripts.pory"
	.string "When this operation's over, I'll take\n"
# 1196 "data/maps/SlateportCity/scripts.pory"
	.string "you to a hot spring spa!\p"
# 1197 "data/maps/SlateportCity/scripts.pory"
	.string "That's what our leader said.\n"
# 1198 "data/maps/SlateportCity/scripts.pory"
	.string "I can't wait!$"
# 1199 "data/maps/SlateportCity/scripts.pory"

# 1200 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SeaIsSoWet:
# 1201 "data/maps/SlateportCity/scripts.pory"
	.string "The sea is just so vast…\p"
# 1202 "data/maps/SlateportCity/scripts.pory"
	.string "Could the sea have been made by\n"
# 1203 "data/maps/SlateportCity/scripts.pory"
	.string "the tears shed by Pokémon?$"
# 1204 "data/maps/SlateportCity/scripts.pory"

# 1205 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SinkOldBoats:
# 1206 "data/maps/SlateportCity/scripts.pory"
	.string "Do you know what they do with old\n"
# 1207 "data/maps/SlateportCity/scripts.pory"
	.string "ships that become too creaky to sail?\p"
# 1208 "data/maps/SlateportCity/scripts.pory"
	.string "They sink them in the sea so they\n"
# 1209 "data/maps/SlateportCity/scripts.pory"
	.string "become habitats for Pokémon.$"
# 1210 "data/maps/SlateportCity/scripts.pory"

# 1211 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BuyTooMuch:
# 1212 "data/maps/SlateportCity/scripts.pory"
	.string "Whenever I visit here, I get carried\n"
# 1213 "data/maps/SlateportCity/scripts.pory"
	.string "away and buy too much.$"
# 1214 "data/maps/SlateportCity/scripts.pory"

# 1215 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_GetNameRaterToHelpYou:
# 1216 "data/maps/SlateportCity/scripts.pory"
	.string "If you want to change your Pokémon's\n"
# 1217 "data/maps/SlateportCity/scripts.pory"
	.string "nickname, you'll have to get the Name\l"
# 1218 "data/maps/SlateportCity/scripts.pory"
	.string "Rater to help you.$"
# 1219 "data/maps/SlateportCity/scripts.pory"

# 1220 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WelcomeToSlateportMarket:
# 1221 "data/maps/SlateportCity/scripts.pory"
	.string "Welcome to the Slateport Market,\n"
# 1222 "data/maps/SlateportCity/scripts.pory"
	.string "The novelty place of Hoenn!\p"
# 1223 "data/maps/SlateportCity/scripts.pory"
	.string "Please accept this gift!$"
# 1224 "data/maps/SlateportCity/scripts.pory"

# 1225 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_EnjoyYourStay:
# 1226 "data/maps/SlateportCity/scripts.pory"
	.string "We hope you enjoy your stay here!$"
# 1227 "data/maps/SlateportCity/scripts.pory"

# 1228 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WelcomeToSlateportMarket2:
# 1229 "data/maps/SlateportCity/scripts.pory"
	.string "Welcome to the Slateport Market,\n"
# 1230 "data/maps/SlateportCity/scripts.pory"
	.string "The novelty place of Hoenn!\p"
# 1231 "data/maps/SlateportCity/scripts.pory"
	.string "We hope you enjoy your stay here!$"
# 1232 "data/maps/SlateportCity/scripts.pory"

# 1233 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BattleTentBuiltRecently:
# 1234 "data/maps/SlateportCity/scripts.pory"
	.string "Recently, a Battle Tent was built\n"
# 1235 "data/maps/SlateportCity/scripts.pory"
	.string "in Slateport.\p"
# 1236 "data/maps/SlateportCity/scripts.pory"
	.string "Gyms are fun, but the Battle Tent's\n"
# 1237 "data/maps/SlateportCity/scripts.pory"
	.string "awesome in its own way.\p"
# 1238 "data/maps/SlateportCity/scripts.pory"
	.string "You should go find tough Pokémon\n"
# 1239 "data/maps/SlateportCity/scripts.pory"
	.string "for the Battle Tent!$"
# 1240 "data/maps/SlateportCity/scripts.pory"

# 1241 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_CaptSternBeingInterviewed:
# 1242 "data/maps/SlateportCity/scripts.pory"
	.string "I was hoping that it was a famous star\n"
# 1243 "data/maps/SlateportCity/scripts.pory"
	.string "so I could get an autograph.\p"
# 1244 "data/maps/SlateportCity/scripts.pory"
	.string "But who's that being interviewed?\n"
# 1245 "data/maps/SlateportCity/scripts.pory"
	.string "Isn't that Capt. Stern?$"
# 1246 "data/maps/SlateportCity/scripts.pory"

# 1247 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_InterviewerSoCool:
# 1248 "data/maps/SlateportCity/scripts.pory"
	.string "That lady interviewer is so cool\n"
# 1249 "data/maps/SlateportCity/scripts.pory"
	.string "and pretty.\p"
# 1250 "data/maps/SlateportCity/scripts.pory"
	.string "When I grow up, I'm going to be\n"
# 1251 "data/maps/SlateportCity/scripts.pory"
	.string "an international journalist!$"
# 1252 "data/maps/SlateportCity/scripts.pory"

# 1253 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternSaysDiscoveredSomething:
# 1254 "data/maps/SlateportCity/scripts.pory"
	.string "Capt. Stern says they discovered\n"
# 1255 "data/maps/SlateportCity/scripts.pory"
	.string "something at the bottom of the sea.\p"
# 1256 "data/maps/SlateportCity/scripts.pory"
	.string "I wonder what it is?\n"
# 1257 "data/maps/SlateportCity/scripts.pory"
	.string "What could it be?$"
# 1258 "data/maps/SlateportCity/scripts.pory"

# 1259 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_NoveltiesAroundTheWorld:
# 1260 "data/maps/SlateportCity/scripts.pory"
	.string "Ho ho ho!\p"
# 1261 "data/maps/SlateportCity/scripts.pory"
	.string "I bring forth novelties from across\n"
# 1262 "data/maps/SlateportCity/scripts.pory"
	.string "the globe!\p"
# 1263 "data/maps/SlateportCity/scripts.pory"
	.string "Might I entice you with the prospect\n"
# 1264 "data/maps/SlateportCity/scripts.pory"
	.string "of procuring any?$"
# 1265 "data/maps/SlateportCity/scripts.pory"

# 1266 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_AmIOnTV:
# 1267 "data/maps/SlateportCity/scripts.pory"
	.string "Hey! Are you watching?\n"
# 1268 "data/maps/SlateportCity/scripts.pory"
	.string "Am I on TV?$"
# 1269 "data/maps/SlateportCity/scripts.pory"

# 1270 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_CaptainsACelebrity:
# 1271 "data/maps/SlateportCity/scripts.pory"
	.string "A TV interview! Here!\n"
# 1272 "data/maps/SlateportCity/scripts.pory"
	.string "The Captain's a celebrity!$"
# 1273 "data/maps/SlateportCity/scripts.pory"

# 1274 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BigSmileForCamera:
# 1275 "data/maps/SlateportCity/scripts.pory"
	.string "Ty: Okay, Capt. Stern, a big smile\n"
# 1276 "data/maps/SlateportCity/scripts.pory"
	.string "for the camera!$"
# 1277 "data/maps/SlateportCity/scripts.pory"

# 1278 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_MostInvaluableExperience:
# 1279 "data/maps/SlateportCity/scripts.pory"
	.string "Gabby: I see, I see. You've had a most\n"
# 1280 "data/maps/SlateportCity/scripts.pory"
	.string "invaluable experience…$"
# 1281 "data/maps/SlateportCity/scripts.pory"

# 1282 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternMoveAheadWithExploration:
# 1283 "data/maps/SlateportCity/scripts.pory"
	.string "Capt. Stern: Yes, indeed. We intend to\n"
# 1284 "data/maps/SlateportCity/scripts.pory"
	.string "move ahead with our exploration.$"
# 1285 "data/maps/SlateportCity/scripts.pory"

# 1286 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_GabbyWonderfulThanksForInterview:
# 1287 "data/maps/SlateportCity/scripts.pory"
	.string "Gabby: That's wonderful, Capt. Stern!\n"
# 1288 "data/maps/SlateportCity/scripts.pory"
	.string "Thank you for taking the time from\l"
# 1289 "data/maps/SlateportCity/scripts.pory"
	.string "your busy schedule to talk to us.\p"
# 1290 "data/maps/SlateportCity/scripts.pory"
	.string "We hope we can interview you again\n"
# 1291 "data/maps/SlateportCity/scripts.pory"
	.string "with news of more discoveries!$"
# 1292 "data/maps/SlateportCity/scripts.pory"

# 1293 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternWhewFirstInterview:
# 1294 "data/maps/SlateportCity/scripts.pory"
	.string "Capt. Stern: Whew…\p"
# 1295 "data/maps/SlateportCity/scripts.pory"
	.string "That was my first time to be filmed for\n"
# 1296 "data/maps/SlateportCity/scripts.pory"
	.string "TV. That was nerve-wracking.$"
# 1297 "data/maps/SlateportCity/scripts.pory"

# 1298 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_OhPlayerWeMadeDiscovery:
# 1299 "data/maps/SlateportCity/scripts.pory"
	.string "Oh! {PLAYER}{KUN}!\n"
# 1300 "data/maps/SlateportCity/scripts.pory"
	.string "You're looking great!\p"
# 1301 "data/maps/SlateportCity/scripts.pory"
	.string "We made a huge discovery on our last\n"
# 1302 "data/maps/SlateportCity/scripts.pory"
	.string "seafloor exploration.\p"
# 1303 "data/maps/SlateportCity/scripts.pory"
	.string "We found an underwater cavern on\n"
# 1304 "data/maps/SlateportCity/scripts.pory"
	.string "Route 128.\p"
# 1305 "data/maps/SlateportCity/scripts.pory"
	.string "We think it's the habitat of a Pokémon\n"
# 1306 "data/maps/SlateportCity/scripts.pory"
	.string "that's said to have been long extinct.$"
# 1307 "data/maps/SlateportCity/scripts.pory"

# 1308 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_AquaWillAssumeControlOfSubmarine:
# 1309 "data/maps/SlateportCity/scripts.pory"
	.string "Fufufu…\n"
# 1310 "data/maps/SlateportCity/scripts.pory"
	.string "Capt. Stern, I presume.\p"
# 1311 "data/maps/SlateportCity/scripts.pory"
	.string "We of Team Aqua will assume\n"
# 1312 "data/maps/SlateportCity/scripts.pory"
	.string "control of your submarine!\p"
# 1313 "data/maps/SlateportCity/scripts.pory"
	.string "Your objections are meaningless!\n"
# 1314 "data/maps/SlateportCity/scripts.pory"
	.string "We expect your total cooperation!\p"
# 1315 "data/maps/SlateportCity/scripts.pory"
	.string "Fufufu…\n"
# 1316 "data/maps/SlateportCity/scripts.pory"
	.string "Just watch and learn what Team\l"
# 1317 "data/maps/SlateportCity/scripts.pory"
	.string "Aqua has planned!$"
# 1318 "data/maps/SlateportCity/scripts.pory"

# 1319 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternWhatWasAllThat:
# 1320 "data/maps/SlateportCity/scripts.pory"
	.string "Capt. Stern: What was that all about?\p"
# 1321 "data/maps/SlateportCity/scripts.pory"
	.string "It sounded like someone using\n"
# 1322 "data/maps/SlateportCity/scripts.pory"
	.string "a megaphone…\p"
# 1323 "data/maps/SlateportCity/scripts.pory"
	.string "Where did it come from?$"
# 1324 "data/maps/SlateportCity/scripts.pory"

# 1325 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_FromHarborTryingToTakeSub:
# 1326 "data/maps/SlateportCity/scripts.pory"
	.string "It's from the Harbor!\p"
# 1327 "data/maps/SlateportCity/scripts.pory"
	.string "The submarine!\n"
# 1328 "data/maps/SlateportCity/scripts.pory"
	.string "They're trying to take it!$"
# 1329 "data/maps/SlateportCity/scripts.pory"

# 1330 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_PleaseComeWithMe:
# 1331 "data/maps/SlateportCity/scripts.pory"
	.string "{PLAYER}{KUN}!\n"
# 1332 "data/maps/SlateportCity/scripts.pory"
	.string "Please, come with me!$"
# 1333 "data/maps/SlateportCity/scripts.pory"

# 1334 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BattleTentSign:
# 1335 "data/maps/SlateportCity/scripts.pory"
	.string "Battle Tent Slateport Site\n"
# 1336 "data/maps/SlateportCity/scripts.pory"
	.string "“Find it! The ultimate Pokémon!”$"
# 1337 "data/maps/SlateportCity/scripts.pory"

# 1338 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternsShipyardWantedSign:
# 1339 "data/maps/SlateportCity/scripts.pory"
	.string "Stern's Shipyard\p"
# 1340 "data/maps/SlateportCity/scripts.pory"
	.string "“Wanted: A sailor capable of sailing\n"
# 1341 "data/maps/SlateportCity/scripts.pory"
	.string "in all currents.”$"
# 1342 "data/maps/SlateportCity/scripts.pory"

# 1343 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternsShipyardNearsCompletion:
# 1344 "data/maps/SlateportCity/scripts.pory"
	.string "Stern's Shipyard\p"
# 1345 "data/maps/SlateportCity/scripts.pory"
	.string "“The ferry S.S. Tidal nears\n"
# 1346 "data/maps/SlateportCity/scripts.pory"
	.string "completion for serving the ports of\l"
# 1347 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport and Lilycove.”$"
# 1348 "data/maps/SlateportCity/scripts.pory"

# 1349 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_SternsShipyardFerryComplete:
# 1350 "data/maps/SlateportCity/scripts.pory"
	.string "Stern's Shipyard\p"
# 1351 "data/maps/SlateportCity/scripts.pory"
	.string "“Boarding of the Slateport-Lilycove\n"
# 1352 "data/maps/SlateportCity/scripts.pory"
	.string "ferry S.S. Tidal is handled at the\l"
# 1353 "data/maps/SlateportCity/scripts.pory"
	.string "Harbor.”$"
# 1354 "data/maps/SlateportCity/scripts.pory"

# 1355 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_PokemonFanClubSign:
# 1356 "data/maps/SlateportCity/scripts.pory"
	.string "Pokémon Fan Club\n"
# 1357 "data/maps/SlateportCity/scripts.pory"
	.string "“Calling all fans of Pokémon!”$"
# 1358 "data/maps/SlateportCity/scripts.pory"

# 1359 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_OceanicMuseumSign:
# 1360 "data/maps/SlateportCity/scripts.pory"
	.string "“The endless sea sustains\n"
# 1361 "data/maps/SlateportCity/scripts.pory"
	.string "all life.”\p"
# 1362 "data/maps/SlateportCity/scripts.pory"
	.string "Oceanic Museum$"
# 1363 "data/maps/SlateportCity/scripts.pory"

# 1364 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_CitySign:
# 1365 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport City\p"
# 1366 "data/maps/SlateportCity/scripts.pory"
	.string "“The port where people and Pokémon\n"
# 1367 "data/maps/SlateportCity/scripts.pory"
	.string "cross paths.”$"
# 1368 "data/maps/SlateportCity/scripts.pory"

# 1369 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_MarketSign:
# 1370 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport Market\n"
# 1371 "data/maps/SlateportCity/scripts.pory"
	.string "“Unique items found nowhere else!”$"
# 1372 "data/maps/SlateportCity/scripts.pory"

# 1373 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_HarborFerryUnderConstruction:
# 1374 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport Harbor\p"
# 1375 "data/maps/SlateportCity/scripts.pory"
	.string "“The ferry S.S. Tidal is under\n"
# 1376 "data/maps/SlateportCity/scripts.pory"
	.string "construction in the Shipyard.\p"
# 1377 "data/maps/SlateportCity/scripts.pory"
	.string "“Service is scheduled to begin\n"
# 1378 "data/maps/SlateportCity/scripts.pory"
	.string "shortly.”$"
# 1379 "data/maps/SlateportCity/scripts.pory"

# 1380 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_HarborSign:
# 1381 "data/maps/SlateportCity/scripts.pory"
	.string "Slateport Harbor\p"
# 1382 "data/maps/SlateportCity/scripts.pory"
	.string "“Enjoy a delightful cruise on\n"
# 1383 "data/maps/SlateportCity/scripts.pory"
	.string "the ferry S.S. Tidal.”$"
# 1384 "data/maps/SlateportCity/scripts.pory"

# 1385 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_NameRatersHouseSign:
# 1386 "data/maps/SlateportCity/scripts.pory"
	.string "Name Rater's House\n"
# 1387 "data/maps/SlateportCity/scripts.pory"
	.string "“Pokémon nicknames rated.”$"
# 1388 "data/maps/SlateportCity/scripts.pory"

# 1389 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ExplainBerries:
# 1390 "data/maps/SlateportCity/scripts.pory"
	.string "If a wild Pokémon gets hurt, it heals\n"
# 1391 "data/maps/SlateportCity/scripts.pory"
	.string "itself by chewing on Berries.\p"
# 1392 "data/maps/SlateportCity/scripts.pory"
	.string "Did you know that?\p"
# 1393 "data/maps/SlateportCity/scripts.pory"
	.string "Somebody saw that and got the idea\n"
# 1394 "data/maps/SlateportCity/scripts.pory"
	.string "of making medicine from Berries.\p"
# 1395 "data/maps/SlateportCity/scripts.pory"
	.string "Did you know that?\p"
# 1396 "data/maps/SlateportCity/scripts.pory"
	.string "To turn Berries into medicine,\n"
# 1397 "data/maps/SlateportCity/scripts.pory"
	.string "they must be crushed into powder.\p"
# 1398 "data/maps/SlateportCity/scripts.pory"
	.string "Did you know that?\p"
# 1399 "data/maps/SlateportCity/scripts.pory"
	.string "You seem to have an interest\n"
# 1400 "data/maps/SlateportCity/scripts.pory"
	.string "in Berries!\p"
# 1401 "data/maps/SlateportCity/scripts.pory"
	.string "I've got something good for someone\n"
# 1402 "data/maps/SlateportCity/scripts.pory"
	.string "like you.$"
# 1403 "data/maps/SlateportCity/scripts.pory"

# 1404 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ExplainBerryPowder:
# 1405 "data/maps/SlateportCity/scripts.pory"
	.string "I recently had machines installed at\n"
# 1406 "data/maps/SlateportCity/scripts.pory"
	.string "Pokémon Centers for crushing Berries.\p"
# 1407 "data/maps/SlateportCity/scripts.pory"
	.string "The Berry Crush machines are at\n"
# 1408 "data/maps/SlateportCity/scripts.pory"
	.string "the Direct Corner upstairs.\p"
# 1409 "data/maps/SlateportCity/scripts.pory"
	.string "Did you know?\p"
# 1410 "data/maps/SlateportCity/scripts.pory"
	.string "Could you make Berry Powder for\n"
# 1411 "data/maps/SlateportCity/scripts.pory"
	.string "me using those machines?\p"
# 1412 "data/maps/SlateportCity/scripts.pory"
	.string "I can make you all sorts of medicine\n"
# 1413 "data/maps/SlateportCity/scripts.pory"
	.string "if you bring me lots of Berry Powder.$"
# 1414 "data/maps/SlateportCity/scripts.pory"

# 1415 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_BroughtMeSomeBerryPowder:
# 1416 "data/maps/SlateportCity/scripts.pory"
	.string "Have you brought me some\n"
# 1417 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder?$"
# 1418 "data/maps/SlateportCity/scripts.pory"

# 1419 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ExchangeWhatWithIt:
# 1420 "data/maps/SlateportCity/scripts.pory"
	.string "What would you like to exchange\n"
# 1421 "data/maps/SlateportCity/scripts.pory"
	.string "it with?$"
# 1422 "data/maps/SlateportCity/scripts.pory"

# 1423 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ExchangeBerryPowderForItem:
# 1424 "data/maps/SlateportCity/scripts.pory"
	.string "Okay, you want to exchange your\n"
# 1425 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder for one {STR_VAR_1}?$"
# 1426 "data/maps/SlateportCity/scripts.pory"

# 1427 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_DontHaveEnoughBerryPowder:
# 1428 "data/maps/SlateportCity/scripts.pory"
	.string "Oh, dear. You don't have enough\n"
# 1429 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder.$"
# 1430 "data/maps/SlateportCity/scripts.pory"

# 1431 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_FineBerryPowderTradeSomethingElse:
# 1432 "data/maps/SlateportCity/scripts.pory"
	.string "This is fine Berry Powder.\n"
# 1433 "data/maps/SlateportCity/scripts.pory"
	.string "It will make excellent medicine.\p"
# 1434 "data/maps/SlateportCity/scripts.pory"
	.string "Would you like to trade more of your\n"
# 1435 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder for something else?$"
# 1436 "data/maps/SlateportCity/scripts.pory"

# 1437 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_WhenYouGetMoreBringItToMe:
# 1438 "data/maps/SlateportCity/scripts.pory"
	.string "Okay! When you get some more\n"
# 1439 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder, bring it to me, please!$"
# 1440 "data/maps/SlateportCity/scripts.pory"

# 1441 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_ComeBackToTradeBerryPowder:
# 1442 "data/maps/SlateportCity/scripts.pory"
	.string "Come back if you'd like to trade your\n"
# 1443 "data/maps/SlateportCity/scripts.pory"
	.string "Berry Powder for some medicine.\p"
# 1444 "data/maps/SlateportCity/scripts.pory"
	.string "I'm always running a bazaar here.\p"
# 1445 "data/maps/SlateportCity/scripts.pory"
	.string "Did you know?$"
# 1446 "data/maps/SlateportCity/scripts.pory"

# 1447 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_YouDroveTeamAquaAway:
# 1448 "data/maps/SlateportCity/scripts.pory"
	.string "Scott: Huh?\n"
# 1449 "data/maps/SlateportCity/scripts.pory"
	.string "I'm sure I met you somewhere before.\p"
# 1450 "data/maps/SlateportCity/scripts.pory"
	.string "Have I introduced myself to you?\n"
# 1451 "data/maps/SlateportCity/scripts.pory"
	.string "If not, my name's Scott.\p"
# 1452 "data/maps/SlateportCity/scripts.pory"
	.string "I just saw Team Aqua run away from\n"
# 1453 "data/maps/SlateportCity/scripts.pory"
	.string "here like they were stung.\p"
# 1454 "data/maps/SlateportCity/scripts.pory"
	.string "Let me guess--you drove them away?$"
# 1455 "data/maps/SlateportCity/scripts.pory"

# 1456 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_MaybeThisTrainer:
# 1457 "data/maps/SlateportCity/scripts.pory"
	.string "Scott: Hmm…\n"
# 1458 "data/maps/SlateportCity/scripts.pory"
	.string "Maybe, just maybe, this Trainer…$"
# 1459 "data/maps/SlateportCity/scripts.pory"

# 1460 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_LetsRegisterEachOther:
# 1461 "data/maps/SlateportCity/scripts.pory"
	.string "Scott: All right! I think you're going\n"
# 1462 "data/maps/SlateportCity/scripts.pory"
	.string "to become a good friend.\p"
# 1463 "data/maps/SlateportCity/scripts.pory"
	.string "So, let's register each other in our\n"
# 1464 "data/maps/SlateportCity/scripts.pory"
	.string "PokéNavs.\p"
# 1465 "data/maps/SlateportCity/scripts.pory"
	.string "… … … … … …$"
# 1466 "data/maps/SlateportCity/scripts.pory"

# 1467 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_RegisteredScott:
# 1468 "data/maps/SlateportCity/scripts.pory"
	.string "Registered this Scott person\n"
# 1469 "data/maps/SlateportCity/scripts.pory"
	.string "in the PokéNav.$"
# 1470 "data/maps/SlateportCity/scripts.pory"

# 1471 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_KeepEyeOnTrainersBeSeeingYou:
# 1472 "data/maps/SlateportCity/scripts.pory"
	.string "Scott: What I'd like to do is tag along\n"
# 1473 "data/maps/SlateportCity/scripts.pory"
	.string "with you, but I do want to keep an eye\l"
# 1474 "data/maps/SlateportCity/scripts.pory"
	.string "on the talents of other people, too.\p"
# 1475 "data/maps/SlateportCity/scripts.pory"
	.string "So, I'll be off to roam other towns\n"
# 1476 "data/maps/SlateportCity/scripts.pory"
	.string "a bit more.\p"
# 1477 "data/maps/SlateportCity/scripts.pory"
	.string "Be seeing you, {PLAYER}{KUN}!$"
# 1478 "data/maps/SlateportCity/scripts.pory"

# 1479 "data/maps/SlateportCity/scripts.pory"
SlateportCity_Text_TakingBattleTentChallenge:
# 1480 "data/maps/SlateportCity/scripts.pory"
	.string "Scott: Oh, hey!\n"
# 1481 "data/maps/SlateportCity/scripts.pory"
	.string "If it isn't {PLAYER}{KUN}!\p"
# 1482 "data/maps/SlateportCity/scripts.pory"
	.string "{PLAYER}{KUN}, let me guess--you're going\n"
# 1483 "data/maps/SlateportCity/scripts.pory"
	.string "to take the Battle Tent challenge?\p"
# 1484 "data/maps/SlateportCity/scripts.pory"
	.string "Yeah! That's a good idea!\n"
# 1485 "data/maps/SlateportCity/scripts.pory"
	.string "That's a really great idea!\p"
# 1486 "data/maps/SlateportCity/scripts.pory"
	.string "After all, a tough Trainer is\n"
# 1487 "data/maps/SlateportCity/scripts.pory"
	.string "the perfect fit for the Battle Tent!\p"
# 1488 "data/maps/SlateportCity/scripts.pory"
	.string "Give it your best effort!$"
