MoveTutor_Text_SwaggerTeach:
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the Chairman\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Swagger to a Pokémon of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to Swagger?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_IceBallTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your Pokémon will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move Ice Ball\n"
	.string "if you'd like.$"

MoveTutor_Text_IceBallDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_IceBallWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the Pokémon looked like me.$"

MoveTutor_Text_IceBallTaught:
	.string "Rolling around makes me happy.\n"
	.string "Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a Bug-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called Fury Cutter.\n"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move Mimic?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach Mimic\n"
	.string "to your Pokémon!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the Pokémon\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "Mimic is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your Pokémon\n"
	.string "the move Metronome.\p"
	.string "Money won't appear, but your Pokémon\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a Pokémon waggles its finger\n"
	.string "like a Metronome, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on Hidden\n"
	.string "Power to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and Sleep Talk.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Sleep Talk instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with Hidden Power, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I Sleep Talk…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a Pokémon learn Substitute?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A Pokémon can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which Pokémon do you want me to\l"
	.string "teach Substitute?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_CloseCombatTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a Fighting-type Trainer,\n"
	.string "so I can't win at the Mossdeep Gym\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only letting my guard down!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon Close Combat?$"

MoveTutor_Text_CloseCombatDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Hiyaaaa!$"

MoveTutor_Text_CloseCombatWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_CloseCombatTaught:
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that Close Combat!\p"
	.string "Hiyaaaa!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Sootopolis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a Double-Edge.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move Double-Edge!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which Pokémon should I teach\n"
	.string "Double-Edge?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge Explosion of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach Explosion to your Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An Explosion it is!\n"
	.string "Which Pokémon wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use Explosion, but I've yet\l"
	.string "to ignite my own Explosion…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"

MoveTutor_Text_GrassyGlideTeach:
	.string "Glide! Glide! Glide!\p"
	.string "What am I doing?\p"
	.string "I'm just yelling my favorite word,\n"
	.string "glide!\p"
	.string "Gliding on grass!\p"
	.string "Do you want me to teach your Pokémon\n"
	.string "to glide on grass?$"

MoveTutor_Text_GrassyGlideDeclined:
	.string "I hope you change your mind about\n"
	.string "about this!$"

MoveTutor_Text_GrassyGlideWhichMon:
	.string "Woo-hoo!\p"
	.string "So which Pokémon should learn\n"
	.string "Grassy Glide?$"

MoveTutor_Text_GrassyGlideTaught:
	.string "Grassy Glide has a cool effect!\p"
	.string "This move always goes first when\n"
	.string "the field is grassy!$"

MoveTutor_Text_ScorchingSandsTeach:
	.string "There's a volcano behind us.\p"
	.string "Its scorching, and its filled with\n"
	.string "mud and rocks… and lava.\p"
	.string "How about I teach one of your\n"
	.string "Pokémon the move to remember this\l"
	.string "occasion?\p"
	.string "Scorching Sands!\p"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_ScorchingSandsDeclined:
	.string "You burnt my soul!$"

MoveTutor_Text_ScorchingSandsWhichMon:
	.string "Hot sands!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_ScorchingSandsTaught:
	.string "Scorching Sands is a really cool move!\p"
	.string "It's a Ground-type move that can\n"
	.string "burn!$"

MoveTutor_Text_SkitterSmackTeach:
	.string "Bugs! Bugs everywhere!\p"
	.string "I love them skittering and buzzing\n"
	.string "around me!\p"
	.string "Hm… You're a Trainer.\p"
	.string "How about I teach Skitter Smack to\n"
	.string "one of your Pokémon?\p"
	.string "Trust me, it's a good attack!$"

MoveTutor_Text_SkitterSmackDeclined:
	.string "Then skitter-scram, nerd!$"

MoveTutor_Text_SkitterSmackWhichMon:
	.string "Wowzers!\n"
	.string "Which bugger's it gonna be?$"

MoveTutor_Text_SkitterSmackTaught:
	.string "Skitter Smack lowers the foe's Sp.\n"
	.string "Attack while also dealing a lot of\l"
	.string "damage!\p"
	.string "Cool, eh?$"

MoveTutor_Text_ExpandingForceTeach:
	.string "Domain Expansion!\p"
	.string "I have mastered the art of expanding\n"
	.string "my domain!\l"
	.string "With the Force\p"
	.string "You're here because you want me to\n"
	.string "teach you this technique?$"

MoveTutor_Text_ExpandingForceDeclined:
	.string "Fair enough…\p"
	.string "I was just guessing.$"

MoveTutor_Text_ExpandingForceWhichMon:
	.string "I knew it!\n"
	.string "So who's gonna weild the\l"
	.string "Expanding Force?$"

MoveTutor_Text_ExpandingForceTaught:
	.string "Expanding Force is a strong move.\p"
	.string "And it only gets stronger and stronger\n"
	.string "in Psychic Terrain!\p"
	.string "Cool, eh?$"

MoveTutor_Text_RisingVoltageTeach:
	.string "Thank you for saving the plant!\p"
	.string "As a reward, I can teach your\n"
	.string "Pokémon, Rising Voltage!\p"
	.string "So, do you want me to teach it?$"

MoveTutor_Text_RisingVoltageDeclined:
	.string "Oh, it's okay!\p"
	.string "Let me know if you change your mind!$"

MoveTutor_Text_RisingVoltageWhichMon:
	.string "Bazinga!\n"
	.string "Whom should I teach it?$"

MoveTutor_Text_RisingVoltageTaught:
	.string "The power of Rising Voltage doubles\n"
	.string "when the field is electrified!\p"
	.string "When used wisely, it can deal lots\n"
	.string "of damage.\p"
	.string "You can make good use of this move!$"

MoveTutor_Text_BraveBirdTeach:
	.string "I am Bo, the Brave!\p"
	.string "As a bird keeper it is my solem duty\n"
	.string "to teach birds how to be brave!\p"
	.string "So, do you want me to teach your birds,\n"
	.string "Brave Bird?$"

MoveTutor_Text_BraveBirdDeclined:
	.string "…!\p"
	.string "If you change your mind, you know!\n"
	.string "where to find me.$"

MoveTutor_Text_BraveBirdWhichMon:
	.string "Huzzah!\n"
	.string "Who will it be?$"

MoveTutor_Text_BraveBirdTaught:
	.string "Its been done!\p"
	.string "Now your Pokémon can majestically take\n"
	.string "down its prey- I mean foe!$"

MoveTutor_Text_FlareBlitzTeach:
	.string "Hi there, Trainer!\p"
	.string "I teach the art of cloaking in flames\n"
	.string "and charging at your foe!\p"
	.string "Would you be interested in learning the\n"
	.string "move, Flare Blitz?$"

MoveTutor_Text_FlareBlitzDeclined:
	.string "Ow, that's a burn!\p"
	.string "I'll be waiting here, if you do.$"

MoveTutor_Text_FlareBlitzWhichMon:
	.string "Furious!\n"
	.string "Choose your warrior!$"

MoveTutor_Text_FlareBlitzTaught:
	.string "Done!\p"
	.string "The fire lives within!$"

MoveTutor_Text_WildChargeTeach:
	.string "Bzzt!\p"
	.string "I know a very powerful Electric-type\n"
	.string "attack!\p"
	.string "Are you interested in learning it?$"

MoveTutor_Text_WildChargeDeclined:
	.string "Big missed opportunity…$"

MoveTutor_Text_WildChargeWhichMon:
	.string "Awesome!\n"
	.string "Wild Charge!$"

MoveTutor_Text_WildChargeTaught:
	.string "Aaand done!\p"
	.string "Have fun Ko'ing your enemies!$"

MoveTutor_Text_MudSlapTeach:
	.string "Oh, hello.\p"
	.string "You wanna learn a move that always\n"
	.string "strikes first?\l"
	.string "And might lower accuracy?$"

MoveTutor_Text_MudSlapDeclined:
	.string "Oh, come on!\n" 
	.string "I'm not joking, I'm serious!$"

MoveTutor_Text_MudSlapWhichMon:
	.string "Epic sauce!\n"
	.string "We throw mud!$"

MoveTutor_Text_MudSlapTaught:
	.string "Done!\p"
	.string "Have fun trolling your enemies!$"

PetalburgCity_PokemonCenter_1F_Text_TutorWelcome:
	.string "Hi.\p"
	.string "I can teach your Pokémon a few moves…$"

PetalburgCity_PokemonCenter_1F_Text_WontTeachMoves:
	.string "Hi.\n"
	.string "I am a Move Tutor.\p"
	.string "I can teach your Pokémon a few moves…\p"
	.string "I see that you haven't beaten Tiana,\n"
	.string "yet.\p"
	.string "Beat her, and then I shall teach you\n"
	.string "my techniques!$"

PetalburgCity_PokemonCenter_1F_Text_WhichMoveTeach:
	.string "Which move should I teach?$"

PetalburgCity_PokemonCenter_1F_Text_TheMoveRight:
	.string "Hmm, {STR_VAR_1}, right?$"

PetalburgCity_PokemonCenter_1F_Text_PleaseChoosePkmn:
	.string "Okay! Please choose your Pokémon.$"

PetalburgCity_PokemonCenter_1F_Text_AndDone:
	.string "Aaand done!\p"
	.string "Please feel free to come again!$"

PetalburgCity_PokemonCenter_1F_Text_PleaseVisitAgain:
	.string "Please let me know if you need anything\n"
	.string "else!$"

PetalburgCity_PokemonCenter_1F_Text_BugBiteDesc::
	.string "A bite that also\n"
	.string "steals and eats\n"
	.string "the foe's berry.$"

PetalburgCity_PokemonCenter_1F_Text_CovetDesc::
	.string "Cutely begs to\n"
	.string "obtain the foe's\n"
	.string "held item.$"

PetalburgCity_PokemonCenter_1F_Text_WaterPulseDesc::
	.string "Pulsing blast of\n"
	.string "water that may\n"
	.string "confuse the foe.$"

PetalburgCity_PokemonCenter_1F_Text_DualChopDesc::
	.string "Attacks foe by\n"
	.string "brutally striking\n"
	.string "it twice.$"

LilycoveCity_DepartmentStore_4F_Text_TutorWelcome:
	.string "Welcome!\p"
	.string "Would you like to teach new moves to\n"
	.string "your Pokémon?$"

LilycoveCity_DepartmentStore_4F_Text_WhichMoveTeach:
	.string "Which move should I teach?$"

LilycoveCity_DepartmentStore_4F_Text_TheMoveIsIt:
	.string "The move {STR_VAR_1}, is it?$"

LilycoveCity_DepartmentStore_4F_Text_PleaseChoosePkmn:
	.string "Okay! Please choose your Pokémon.$"

LilycoveCity_DepartmentStore_4F_Text_AndDone:
	.string "Aaand done!\p"
	.string "Please let me know if you need anything\n"
	.string "else!$"

LilycoveCity_DepartmentStore_4F_Text_PleaseVisitAgain:
	.string "Please let me know if you need anything\n"
	.string "else!$"

LilycoveCity_DepartmentStore_4F_Text_OverheatDesc::
	.string "An intense heat\n"
	.string "harshly lowers the\n"
	.string "user's Sp. Atk.$"

LilycoveCity_DepartmentStore_4F_Text_LeafStormDesc::
	.string "A storm of leaves\n"
	.string "harshly lowers the\n"
	.string "user's Sp. Atk.$"

LilycoveCity_DepartmentStore_4F_Text_SheerColdDesc::
	.string "An intense cold\n"
	.string "harshly lowers the\n"
	.string "user's Sp. Atk.$"

LilycoveCity_DepartmentStore_4F_Text_DracoMeteorDesc::
	.string "A comet attack\n"
	.string "harshly lowers the\n"
	.string "user's Sp. Atk.$"

LilycoveCity_DepartmentStore_4F_Text_FoulPlayDesc::
	.string "Uses the foe's\n"
	.string "attack stat to\n"
	.string "deal damage.$"

LilycoveCity_DepartmentStore_4F_Text_SkyAttackDesc::
	.string "Deals a lot of\n"
	.string "damage, but also\n"
	.string "lowers defenses.$"

LilycoveCity_DepartmentStore_4F_Text_InfestationDesc::
	.string "Traps the foe\n"
	.string "for 3-5 turns in\n"
	.string "an infestation.$"

LilycoveCity_DepartmentStore_4F_Text_FireSpinDesc::
	.string "Traps the foe\n"
	.string "for 3-5 turns in\n"
	.string "a fire storm.$"

LilycoveCity_DepartmentStore_4F_Text_WhirlpoolDesc::
	.string "Traps the foe\n"
	.string "for 3-5 turns in\n"
	.string "a whirlpool.$"

LilycoveCity_DepartmentStore_4F_Text_PainSplitDesc::
	.string "Adds the user and\n"
	.string "foe's HP, then\n"
	.string "equally shares it.$"

NewMauville_Inside_EventScript_SuperpowerTutor::
	.string "Deals a lot of\n"
	.string "damage, but lowers\n"
	.string "physical stats.$"

MoveTutor_Text_RazorShellTeach:
	.string "I can teach you a move.\n"
	.string "A strong, slicing move.\l"
	.string "It can slice through anything.\l"
	.string "… … … … …\l"
	.string "… … … … …\p"
	.string "Would you like to learn Razor Shell?$"

MoveTutor_Text_RazorShellDeclined:
	.string "It's fine!\p"
	.string "I'll be here, if you change your mind.$"

MoveTutor_Text_RazorShellWhichMon:
	.string "You made the right choice!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_RazorShellTaught:
	.string "Razor Shell is a strong, slicing move\n"
	.string "which may also lower the enemy's\l"
	.string "defense!$"
