# 1 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 2 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_MapScripts::
# 3 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.byte 0
# 4 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 5 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Grunt5::
# 6 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_Text_Grunt5Intro, SeafloorCavern_Room3_Text_Grunt5Defeat
# 7 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 9 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 10 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Grunt6::
# 11 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_6, SeafloorCavern_Room3_Text_Grunt6Intro, SeafloorCavern_Room3_Text_Grunt6Defeat
# 12 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_Grunt6PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 14 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 15 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Intro:
# 16 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "For our dream to become real, we need\n"
# 17 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "the power of Pokémon.\p"
# 18 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "But meddlers like you use the power of\n"
# 19 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Pokémon to mess with us even at\l"
# 20 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "a place like this!\p"
# 21 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Life just doesn't work the way we\n"
# 22 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "need it to!$"
# 23 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 24 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Defeat:
# 25 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Gwah!$"
# 26 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 27 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5PostBattle:
# 28 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "You know, we don't dare question\n"
# 29 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "the motives of our leader.\p"
# 30 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "But here you are, just some punk,\n"
# 31 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "going up against our Boss.\p"
# 32 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Maybe…\n"
# 33 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "You must be something…$"
# 34 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 35 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6Intro:
# 36 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "You Trainers will perish when we\n"
# 37 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "achieve our goals!$"
# 38 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 39 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6Defeat:
# 40 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Why won't you let us win for once?$"
# 41 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 42 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6PostBattle:
# 43 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Sometimes I think whether we're\n"
# 44 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "right or wrong…\p"
# 45 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Then, twerps like you show up and\n"
# 46 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "motivate me to work towards our goal!$"
